<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Approve Button</name>
   <tag></tag>
   <elementGuidId>70209a7d-fa1e-42a6-95aa-634ac0e564de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fk-approve-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-approve-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e151973-37c0-4d2c-8dc7-229b43d56e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>common__SecondaryButton-sc-khnafi-1 fSfAnN fk-secondary-button fk-approve-button</value>
      <webElementGuid>3580e440-da14-4c77-867c-41773d51779f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-approve-button</value>
      <webElementGuid>1320db9d-fdc5-4023-8766-cbe9097a9c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>0a4f838a-f3ce-4d27-9721-d33bb28204ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-approve-button&quot;)</value>
      <webElementGuid>aa2f3e5d-f21d-45e6-ba74-3c46a9fe5abd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fk-approve-button']</value>
      <webElementGuid>92b88a7e-c4a5-438a-9c44-af84ee82459f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-video-player-container']/div/div[4]/button</value>
      <webElementGuid>6f4344b5-1b54-4402-82d4-8f688e87eabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What would You Like Us to Improve in 2023?'])[1]/following::button[1]</value>
      <webElementGuid>117242bf-a19c-4fd9-939b-b22403ba91cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 1 / 4'])[1]/following::button[1]</value>
      <webElementGuid>f2e51f5f-5720-4bc9-9d69-0ebdd84b470e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rerecord'])[1]/preceding::button[1]</value>
      <webElementGuid>f393a8d4-5449-4de7-a367-fbdb42fd5ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f72247d5-9d14-42f5-b644-ce067e0ecde1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fk-approve-button' and (text() = 'Approve' or . = 'Approve')]</value>
      <webElementGuid>fb95a66b-1d7e-4321-a873-d69bebcc67c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
