<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Rerecord</name>
   <tag></tag>
   <elementGuidId>c599f268-283d-428d-a3a3-861cb51ca7b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fk-retake-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-retake-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7bd0b756-96a2-4277-9702-43b131cac801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>common__LinkButton-sc-khnafi-2 iIhcOB fk-link-button fk-retake-button</value>
      <webElementGuid>ca5b5784-d761-430f-aa82-9cab96d00b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-retake-button</value>
      <webElementGuid>1d78eece-56c3-44ac-b00e-43e3c0270368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rerecord</value>
      <webElementGuid>035c4826-367d-4a80-9bcb-f74bed0fc1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-retake-button&quot;)</value>
      <webElementGuid>5014dc17-ce29-426c-8e6f-c7ace18e6c76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fk-retake-button']</value>
      <webElementGuid>102293ee-ac17-40f2-9ffe-f5dfdbcf173b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-video-player-container']/div/div[4]/button[2]</value>
      <webElementGuid>12ab791f-0b66-4e23-bbdc-a461c90d31d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/following::button[1]</value>
      <webElementGuid>14f97b63-7dcf-4d5b-9a97-dd4ea56b280d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What would You Like Us to Improve in 2023?'])[1]/following::button[2]</value>
      <webElementGuid>ff20b1b4-af04-4191-b6f9-111aadbdf726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>968a033a-97d3-4fc2-be93-c153804d834e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>dabc77a5-ad2c-4884-9fee-4b7b104ba7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rerecord']/parent::*</value>
      <webElementGuid>d50ff75e-da25-4c3b-9f17-997ffb7daafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>2968a8ee-9bbd-4f8b-9c0f-3c65335011a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fk-retake-button' and (text() = 'Rerecord' or . = 'Rerecord')]</value>
      <webElementGuid>8046f664-e754-45b4-9855-3f76a4f115b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
