<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox on Homepage</name>
   <tag></tag>
   <elementGuidId>3ce15969-6638-457a-ae9f-ca27c1a98d2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fk-permission-checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-permission-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f29773f-8106-4a33-881a-bd5d29767d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-permission-checkbox</value>
      <webElementGuid>039b70b4-5dff-4fa6-9eeb-64a4553e2945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fb5cecef-713e-420a-bd60-0c7c4c14ece4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6a2cba0a-b59f-435c-a45c-3550cb337716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check-permission</value>
      <webElementGuid>36e19bb1-ad30-4298-8be4-271916d3bd38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-permission-checkbox&quot;)</value>
      <webElementGuid>f924bad7-74bd-42da-8941-52b10529936e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fk-permission-checkbox']</value>
      <webElementGuid>62b02672-18e5-4d26-815f-a24a43f1df8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-permission-check-wrapper']/input</value>
      <webElementGuid>146cade4-5544-446f-a80a-2ce48f41d65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b77a7fb1-c54c-482a-a686-27f568f71334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fk-permission-checkbox' and @type = 'checkbox' and @name = 'check-permission']</value>
      <webElementGuid>c93c8825-b326-44f7-bfa4-a7cf84a1be33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
