<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Get Started Button</name>
   <tag></tag>
   <elementGuidId>0302efbd-401e-4797-adad-fab19e0ee505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fk-get-started-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-get-started-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>935c249c-7889-47c9-8574-cd73789b02cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-get-started-button</value>
      <webElementGuid>2ffa3f77-3045-45af-a9d0-93b6d0a01104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>common__PrimaryButton-sc-khnafi-0 gEoqgS</value>
      <webElementGuid>6874ee41-3056-48c0-9271-a93674ecaa31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Started</value>
      <webElementGuid>b62a58d9-379e-4998-8763-ce5d676385e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-get-started-button&quot;)</value>
      <webElementGuid>0b060ec1-862a-4c88-bf0e-e80c4f4d7c99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fk-get-started-button']</value>
      <webElementGuid>2bb1a32e-3d96-457c-a75b-b96183a7f5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-mobile-question-screen']/button</value>
      <webElementGuid>5a3f6b4f-dc30-4f7e-af20-d9f2e726ce33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upcoming Questions'])[1]/following::button[1]</value>
      <webElementGuid>da022890-2821-460a-ad00-17c76fe12f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Before approving your feedback, you can review what you recorded and rerecord, if needed.'])[1]/preceding::button[1]</value>
      <webElementGuid>d8eb8cbe-1dfc-48a3-92f5-1ae8f1852774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>08c899a2-f929-42a8-bad4-dccb53a7746f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get Started']/parent::*</value>
      <webElementGuid>6fe2c0ea-4ff5-44a7-a011-e94f1dd09f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c99ab641-d80e-4df7-84d9-a3370d8f6b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fk-get-started-button' and (text() = 'Get Started' or . = 'Get Started')]</value>
      <webElementGuid>8114447d-7462-442e-99ce-030655f76d82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
