<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home Screen Heading</name>
   <tag></tag>
   <elementGuidId>ebd2f94c-f299-4d6f-9ea7-e7c92b30ea7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='fk-homescreen-heading']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fk-homescreen-heading']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-homescreen-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9202b5d0-f641-4684-b7e3-d9af5edc3bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-homescreen-heading</value>
      <webElementGuid>0013c0ff-9151-416f-ba4c-bfea9b0b188d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobileStyle__HomescreenHeading-sc-16wqda4-3 ensJBg</value>
      <webElementGuid>9a07a6a1-34e0-4807-98c2-71407b44b3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation Testing</value>
      <webElementGuid>28a5111d-cc2f-402e-bb5d-62bce69a9bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-homescreen-heading&quot;)</value>
      <webElementGuid>9d4796b6-b020-4df5-b60a-d14f4e88a73f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='fk-homescreen-heading']</value>
      <webElementGuid>57255ad4-44e3-4348-ab4f-892774f6c4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-homescreen-branding-wrapper']/span</value>
      <webElementGuid>d958eb8c-8024-43be-8ad2-15ed4fdbe8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation testing Experience Side'])[1]/preceding::span[1]</value>
      <webElementGuid>e3e7d6ed-1b73-4e19-88e4-db3828262d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::span[3]</value>
      <webElementGuid>ae3d294b-be2c-4835-a3e0-790924b246d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automation Testing']/parent::*</value>
      <webElementGuid>5118a224-9eb6-41ee-acd1-f68656a58f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>fd84747e-8ca3-4fa3-a86a-666467b96cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'fk-homescreen-heading' and (text() = 'Automation Testing' or . = 'Automation Testing')]</value>
      <webElementGuid>f45544e7-a3d0-45b6-a307-614f48e527f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
