<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Next Question Button</name>
   <tag></tag>
   <elementGuidId>5d9252d2-a37a-4b8c-ac50-c381fdd54d73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fk-video-capture-overlay']/div[4]/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b24f7cb8-946d-4c36-8ea3-08a5b8fec961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>3d9a5634-ea92-4f44-b6b6-e8a447a03a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next ></value>
      <webElementGuid>b917deb6-ae5b-4c1a-b300-2b348589166d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-video-capture-overlay&quot;)/div[@class=&quot;fk-video-capture-actions-wrapper&quot;]/div[@class=&quot;fk-video-capture-content&quot;]/div[@class=&quot;fk-video-question-carousel&quot;]/span[@class=&quot;next&quot;]</value>
      <webElementGuid>f67baa97-c13c-41c4-9374-7208c80ada75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-video-capture-overlay']/div[4]/div/div/span[2]</value>
      <webElementGuid>996c408b-65dd-4755-b472-9ebcebafe452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 1 / 4'])[1]/following::span[1]</value>
      <webElementGuid>14b82e3a-7e03-4a8b-957c-1e6e0866f10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt; Prev'])[1]/following::span[1]</value>
      <webElementGuid>1dcfb934-5cb7-4bec-a268-3bd0cb05e9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is your opinion about Fanvoice testing?'])[1]/preceding::span[1]</value>
      <webElementGuid>eb85330a-a2e3-4d91-9175-ed2a94e7442d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Recording'])[1]/preceding::span[1]</value>
      <webElementGuid>884ed6ab-a8de-40db-a56f-ddc07af6ae23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>790237cb-2675-47b2-a23b-7bba29a2d2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>27fcccd4-391b-445a-affb-11aac3d5a19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Next >' or . = 'Next >')]</value>
      <webElementGuid>a9775d66-bce0-48cb-ac50-df33a8ec6703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
