<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Prev Question Button</name>
   <tag></tag>
   <elementGuidId>fdfbfd03-fd44-496e-8db7-7935850e02b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.prev</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fk-video-capture-overlay']/div[4]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2a8959bc-7803-4648-b2e8-f2441a49c0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prev</value>
      <webElementGuid>ec89aef1-5688-4ab2-b79f-870ef5f6ece4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt; Prev</value>
      <webElementGuid>1a904801-80e9-411f-b89a-2b82f29359b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-video-capture-overlay&quot;)/div[@class=&quot;fk-video-capture-actions-wrapper&quot;]/div[@class=&quot;fk-video-capture-content&quot;]/div[@class=&quot;fk-video-question-carousel&quot;]/span[@class=&quot;prev&quot;]</value>
      <webElementGuid>96ac81b9-f5ee-4832-bcba-0baf5af6b0ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-video-capture-overlay']/div[4]/div/div/span</value>
      <webElementGuid>cc9fc462-9c8f-467b-8b15-309e7e893d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 1 / 4'])[1]/preceding::span[1]</value>
      <webElementGuid>bb6d1dab-ad3f-447b-90f9-6e50582c8918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next >'])[1]/preceding::span[1]</value>
      <webElementGuid>4be1dc3e-4f37-4be2-8c07-e9a535537e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;']/parent::*</value>
      <webElementGuid>d747a046-83e3-4ed4-81f2-e0d8d14654ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span</value>
      <webElementGuid>4c1358b2-e9c7-4952-adcc-79e23493f684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '&lt; Prev' or . = '&lt; Prev')]</value>
      <webElementGuid>3d10f9b6-9490-41a3-a252-7e6fdb9aa00d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
