<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rerecord Yes Button</name>
   <tag></tag>
   <elementGuidId>ed2ecd62-f6e2-464d-8ad3-ba39d06c8076</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fk-confirmation-overlay-yes-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-confirmation-overlay-yes-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74e702c0-c747-4a63-ace7-4cb1acd730bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-confirmation-overlay-yes-button</value>
      <webElementGuid>463d1310-616d-4f0a-94b3-e60466494768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__ConfirmButton-sc-3s4d5o-4 fxSqAg</value>
      <webElementGuid>c6002ee1-fdb3-46cd-8941-f42bf3547c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>7ebebf37-5af1-4b30-8fdc-60d7c7e268c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-confirmation-overlay-yes-button&quot;)</value>
      <webElementGuid>84af5006-21dc-442b-9ea5-a3d60589aa94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fk-confirmation-overlay-yes-button']</value>
      <webElementGuid>13ce518d-0e5c-4081-967b-3cb2a602ea89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='fk-automationtestingbywaqas009 fk-experience-mobile']/div/div/div/button</value>
      <webElementGuid>efb61179-46be-4006-8955-36d3be76c7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to discard this response?'])[1]/following::button[1]</value>
      <webElementGuid>72845f7f-80da-46b4-90bd-629584ce42a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rerecord'])[1]/following::button[1]</value>
      <webElementGuid>73eeefd0-e66d-440f-936d-f53f3af815e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>ef6f60aa-d6e5-4cea-9267-fe226fc80a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[1]/preceding::button[2]</value>
      <webElementGuid>db7c1cb5-84a0-4679-bf90-b4db26978a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>02a20dd4-f4ca-436f-a2f5-9455a9bd85df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9098e647-5aaa-49b3-8a8c-74c7a0d1c71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fk-confirmation-overlay-yes-button' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>6f30c4df-bbd9-48ae-97e3-3b670de7ddae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
