<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rerecord No Button</name>
   <tag></tag>
   <elementGuidId>6b9dc881-828d-4a9b-b58d-5cf581e5fbd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fk-confirmation-overlay-no-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-confirmation-overlay-no-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2c548fa-63c8-41a6-8050-d168d1120522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-confirmation-overlay-no-button</value>
      <webElementGuid>a10b44e0-f595-4784-90bb-0527887bfc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__CancelButton-sc-3s4d5o-5 bIatxu</value>
      <webElementGuid>435eea70-4509-4d0e-bc4b-f0c2d920dac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>a66259a9-3cb8-4b89-b0cb-d612763a0ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-confirmation-overlay-no-button&quot;)</value>
      <webElementGuid>d00860bb-003d-4e67-a6d8-414fc236b4b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fk-confirmation-overlay-no-button']</value>
      <webElementGuid>fff6e6ca-e554-4f9f-a1dc-0fd5d7b1ad81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='fk-automationtestingbywaqas009 fk-experience-mobile']/div/div/div/button[2]</value>
      <webElementGuid>50f42200-216f-4b48-8ebf-2b8ebbfe92c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::button[1]</value>
      <webElementGuid>923f1a15-bc06-4295-8b8f-d56c2c2906e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to discard this response?'])[1]/following::button[2]</value>
      <webElementGuid>446e60a0-5b10-4cd1-ad12-1aefdb65c545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[1]/preceding::button[1]</value>
      <webElementGuid>09949c65-56ad-4162-aca3-828b7efe4458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 1 / 4'])[1]/preceding::button[1]</value>
      <webElementGuid>2045125b-9023-4353-8de9-cb7256b0ca9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No']/parent::*</value>
      <webElementGuid>023108c4-12c5-4a07-b4e9-aac4c8a044ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>86c97657-907d-42b4-8410-3107aec207a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fk-confirmation-overlay-no-button' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>63ade420-b008-4759-b023-cb8a82c68bdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
