<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Timer at top</name>
   <tag></tag>
   <elementGuidId>3e45b4d7-241b-4318-9bf0-9c1b8fa8b955</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fk-recording-timer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fk-video-capture-overlay']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>566d7b3a-aadc-437f-a8b8-80d7f1ecc6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fk-recording-timer</value>
      <webElementGuid>f98a6453-0bd0-4111-a2e3-c0fcbf951f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00:20</value>
      <webElementGuid>3cc196ef-0870-4976-a9f9-e79ccc5f355f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-video-capture-overlay&quot;)/div[@class=&quot;fk-recording-timer&quot;]</value>
      <webElementGuid>423e9d41-b170-486d-8afa-30647de37ab8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-video-capture-overlay']/div[2]</value>
      <webElementGuid>b8ee969d-e4ec-4111-ad00-1f461f32c096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt; Prev'])[1]/preceding::div[9]</value>
      <webElementGuid>ce6ecb6e-7764-437a-ad4d-c3774ca7aafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 1 / 4'])[1]/preceding::div[9]</value>
      <webElementGuid>c120be58-02b0-4f68-a974-0dcfc4cf6180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='00:20']/parent::*</value>
      <webElementGuid>e1c14154-9809-4727-9707-754e248f8f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>facd3c60-0500-49d5-922d-a43977d99e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '00:20' or . = '00:20')]</value>
      <webElementGuid>660d16c9-c1eb-47b6-ab04-2db902f4c9ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
