<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add User</name>
   <tag></tag>
   <elementGuidId>5d17a179-42da-4470-a3dc-d33bb7ab25d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sharedStyles__UtilitiesDiv-sc-67rum6-1.iWidAI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed5b8a5c-f2b2-401c-b5b1-35f44ffaf293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sharedStyles__UtilitiesDiv-sc-67rum6-1 iWidAI</value>
      <webElementGuid>5ff275b1-ea7a-425d-92fc-7659e67944f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+  Add User</value>
      <webElementGuid>dda964a4-7116-41d1-acdf-f0ddcded8fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;style__DashboardStyle-sc-1265zxf-0 hpOElW&quot;]/div[@class=&quot;sharedStyles__DashboardMainContainerStyle-sc-67rum6-6 fQHQWc&quot;]/div[@class=&quot;style__SubHeaderStyled-sc-18x0jlo-0 fQAbGU&quot;]/div[@class=&quot;sharedStyles__UtilitiesDiv-sc-67rum6-1 iWidAI&quot;]</value>
      <webElementGuid>1ea36a63-d78c-42f5-9918-453e3dd1eb9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div/div[2]</value>
      <webElementGuid>5aaaf6e9-65ff-4432-8052-769625578807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i'])[1]/following::div[1]</value>
      <webElementGuid>958fdc18-91ed-4ab6-a4ff-18536010a431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Management'])[1]/following::div[3]</value>
      <webElementGuid>e2436633-83ba-4d52-b9ec-31e336597e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMAIL'])[1]/preceding::div[2]</value>
      <webElementGuid>9102018f-8e2d-4d77-8c7d-dd832788f32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]</value>
      <webElementGuid>64b22f9d-3717-4bd0-87e7-1083c851f1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '+  Add User' or . = '+  Add User')]</value>
      <webElementGuid>8133e020-f37a-4ffe-94a9-68b6d4ddbdb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
