<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Too many failed attempts_VfPpkd-muHVF_8ead10</name>
   <tag></tag>
   <elementGuidId>af17637f-bfbb-4107-a7b7-671d8489afb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.VfPpkd-muHVFf-bMcfAe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27a838f5-f3b6-4f4b-8af7-b52f662a451b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VfPpkd-muHVFf-bMcfAe</value>
      <webElementGuid>7e9609ec-edd6-4b55-b64f-d01332a75071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b3d8b699-1882-4952-9166-58ad2147300c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>YPqjbf</value>
      <webElementGuid>9f83e95b-0559-4225-9b73-2fb89b645d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>focus:AHmuwe; blur:O22p3e; change:WPi0i;</value>
      <webElementGuid>c5144a94-7041-40ae-bcdf-82e1468c6e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>selectionc0</value>
      <webElementGuid>39d26dca-398c-42fe-a68a-cad7239a13e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view_container&quot;)/div[@class=&quot;zWl5kd&quot;]/div[@class=&quot;DRS7Fe bxPAYd k6Zj8d&quot;]/div[@class=&quot;pwWryf bxPAYd&quot;]/div[@class=&quot;Wxwduf Us7fWe JhUD8d&quot;]/div[@class=&quot;WEQkZc&quot;]/div[@class=&quot;bCAAsb&quot;]/form[1]/span[1]/section[@class=&quot;aTzEhb&quot;]/div[@class=&quot;CxRgyd&quot;]/div[1]/div[@class=&quot;SdBahf Fjk18&quot;]/div[@class=&quot;EcjFDf&quot;]/div[@class=&quot;IhH7Wd&quot;]/div[@class=&quot;ci67pc&quot;]/div[@class=&quot;BudEQ rBUW7e&quot;]/div[@class=&quot;sSzDje NEk0Ve&quot;]/div[@class=&quot;enBDyd&quot;]/div[@class=&quot;VfPpkd-MPu53c VfPpkd-MPu53c-OWXEXe-dgl2Hf Ne8lhe swXlm az2ine y5MMGc sD2Hod VfPpkd-MPu53c-OWXEXe-mWPk3d VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc VfPpkd-ksKsZd-mWPk3d-OWXEXe-AHe6Kc-XpnDCe&quot;]/input[@class=&quot;VfPpkd-muHVFf-bMcfAe&quot;]</value>
      <webElementGuid>f9e4149a-c05c-4c5f-9483-d303b3302327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>d63baa45-04b8-4163-a23e-0d6e419f5a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_container']/div/div/div[2]/div/div/div/form/span/section/div/div/div/div[3]/div/div/div/div/div/div/input</value>
      <webElementGuid>591a47da-fa1b-4031-be68-5695408a9e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/input</value>
      <webElementGuid>fcd63d5e-fec9-40b6-a45a-76cad5e5ec79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>b1c01f91-f3c8-4f14-8cdb-722a6dcd723c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
