<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox on homepage</name>
   <tag></tag>
   <elementGuidId>0f832741-f1a4-4dc6-9a75-d4240b5ecf38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk-permission-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fk-permission-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d0f978c-dc55-414b-80de-f064c20c8bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-permission-checkbox</value>
      <webElementGuid>6d64468f-0860-44b7-9ada-0bd7bd03944c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6f33a5ac-c297-4d58-8d4f-883bf73632fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>48758016-6c34-4092-be01-30d7eefe4480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check-permission</value>
      <webElementGuid>9dc7b0d0-15d4-4e43-acd0-b40a1d975b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-permission-checkbox&quot;)</value>
      <webElementGuid>0755433f-2950-48a6-a88b-8974b2e48c6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fk-permission-checkbox']</value>
      <webElementGuid>c678f72f-6cfd-4e41-9e77-487894a52eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-permission-check-wrapper']/input</value>
      <webElementGuid>1ec6282b-1a07-470f-85ae-ec5b2b5639f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>40af7524-57c4-4068-97ed-795ace3d54a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fk-permission-checkbox' and @type = 'checkbox' and @name = 'check-permission']</value>
      <webElementGuid>b7e05b51-40e7-444c-9414-2fd0d2b7616a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
