<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Permission Checkbox</name>
   <tag></tag>
   <elementGuidId>a84aa8ab-56ef-4edc-ba01-b5ceaeadc6bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk-permission-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fk-permission-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be533e40-1d81-4172-872f-fa9ba4bf2e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-permission-checkbox</value>
      <webElementGuid>4e075e09-0e45-4061-b337-3cd880985879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a0832125-dcf4-4237-b129-ba072a523322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c26bb039-2177-4fd9-95a4-a9ec67a6e26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check-permission</value>
      <webElementGuid>fdaf206d-deaf-4c29-a7fb-662b41ec77f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-permission-checkbox&quot;)</value>
      <webElementGuid>d6d42bd0-a530-4a80-acaa-4357ef982322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fk-permission-checkbox']</value>
      <webElementGuid>34a4e139-ea7c-46fa-b3c7-38487e77a06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-permission-check-wrapper']/input</value>
      <webElementGuid>19bf36c2-e053-47c8-9bfa-09de799b0606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>555dd089-2b57-4c51-9f19-5b7386bd097b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fk-permission-checkbox' and @type = 'checkbox' and @name = 'check-permission']</value>
      <webElementGuid>a92a34e1-002a-4822-8db8-7123a5867f9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
