<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rerecord button No</name>
   <tag></tag>
   <elementGuidId>938e8eb6-8909-4753-a4b4-3b8c410ae969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk-confirmation-overlay-no-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fk-confirmation-overlay-no-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8d125ce-f110-4237-ac6d-dc8255ab08b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-confirmation-overlay-no-button</value>
      <webElementGuid>2a5c42f5-fdf3-4aab-9143-d8ca2923065b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__CancelButton-sc-3s4d5o-5 bIatxu</value>
      <webElementGuid>e810af77-078a-4c98-8356-7d7ba988e8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>16ea0f83-746c-45cf-abed-0b4e3c91b169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-confirmation-overlay-no-button&quot;)</value>
      <webElementGuid>89f71cc5-9855-42fa-8495-d569be1cf26f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fk-confirmation-overlay-no-button']</value>
      <webElementGuid>bdf03a84-f903-477a-a71e-2a7a6ea9ee5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='fk-automationtestingbywaqas009 fk-experience-mobile']/div/div/div/button[2]</value>
      <webElementGuid>fd8f52d4-4e82-4a09-b51c-d8c02e094c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::button[1]</value>
      <webElementGuid>6142d033-08c1-4f0c-9a73-7db71531cf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to discard this response?'])[1]/following::button[2]</value>
      <webElementGuid>947395b8-13cf-4c6d-8dbc-84ac82b474aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 1 / 2'])[1]/preceding::button[1]</value>
      <webElementGuid>352f732c-64f6-42fa-a0e1-ae406beec4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What would You Like Us to Improve in 2023?'])[1]/preceding::button[1]</value>
      <webElementGuid>209d1686-5511-4964-a976-0ac377e759e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No']/parent::*</value>
      <webElementGuid>19323400-dde0-427b-915e-54dc378b307c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>1c8362b9-fe6e-40db-ab54-1f545c3cd357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fk-confirmation-overlay-no-button' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>ddd7231b-eec5-4487-9050-f5e00f78c6d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
