<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rerecord Button Yes</name>
   <tag></tag>
   <elementGuidId>9173562d-58ad-440f-a967-9d4b9203d2bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk-confirmation-overlay-yes-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fk-confirmation-overlay-yes-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7e4cf0cc-d419-4686-b1e2-3aefe0ca215b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-confirmation-overlay-yes-button</value>
      <webElementGuid>4e52a1e7-6b07-4ca2-b3fe-c3ed491eb152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__ConfirmButton-sc-3s4d5o-4 fxSqAg</value>
      <webElementGuid>072248f2-fe95-4912-b5dd-1f4743fb19f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>1eb4c5b4-0f14-4af2-bc39-47bd32d605ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-confirmation-overlay-yes-button&quot;)</value>
      <webElementGuid>0fa9acaf-49c6-451b-9429-5632bfcb697e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fk-confirmation-overlay-yes-button']</value>
      <webElementGuid>252f9d1a-f722-492e-8757-62e8eb38308d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='fk-automationtestingbywaqas009 fk-experience-mobile']/div/div/div/button</value>
      <webElementGuid>0f59a421-b295-4c1e-810f-a394d458f45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to discard this response?'])[1]/following::button[1]</value>
      <webElementGuid>bf54da14-aa3d-4d27-978c-06c7812f23a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rerecord'])[1]/following::button[1]</value>
      <webElementGuid>c1cd69d4-45e0-4d3d-93a6-05a5729bd3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>221a2fdf-a993-45b3-84f9-0c03856c0d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 1 / 2'])[1]/preceding::button[2]</value>
      <webElementGuid>8d62e692-1df8-4fa9-8402-5fcfcbbc0d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>cee8ac6a-fbc0-470a-9e12-15606bcbb434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a50a3eb4-7a25-47fb-ba88-4345beac5ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fk-confirmation-overlay-yes-button' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>875636af-8509-4a0c-8173-3e999480ac0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
