<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Start Recording Button</name>
   <tag></tag>
   <elementGuidId>04dee64c-7ec2-48c0-b143-4d3597476060</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>854a05de-ffda-4f07-80b3-b4ed1eb84a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>27.5</value>
      <webElementGuid>ae39578c-4b5c-4eee-80c4-2c6952167e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>27.5</value>
      <webElementGuid>464ff057-1ac7-4c94-8575-91f701a86d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>25.5</value>
      <webElementGuid>a8e9bcdd-ec81-497d-ac96-2239d9f01e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#ff6161</value>
      <webElementGuid>34373b81-4b06-462c-82b7-c5667280d280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>8c5dcdfe-82fb-4f96-8d7e-ce28d05e4dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8d83c172-a7a7-4b48-9575-7f2133fd864f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-audio-record-icon&quot;)/svg[1]/circle[1]</value>
      <webElementGuid>e8e7fcb7-456d-4fa6-9714-871adb6db6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-audio-record-icon</value>
      <webElementGuid>862af271-dbdc-4648-ab2c-0f36a729acf3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
