<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Thank You Heading</name>
   <tag></tag>
   <elementGuidId>484d4fa3-7c9f-4eb5-ab03-0d1b348a5ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk-thankyou-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='fk-thankyou-heading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>061f362b-d150-45e2-b07f-ae5decc5adc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-thankyou-heading</value>
      <webElementGuid>bd05be8d-f151-45ee-9568-7044e4fc8441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__BrandHeading-sc-hb79k5-2 style__ThankYouHeading-sc-1991k12-4 bBagrn bzUkAO</value>
      <webElementGuid>0e109876-0277-4401-97e6-dd5771baab65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you!</value>
      <webElementGuid>e959cdaf-79a6-4621-bc8f-e1eb0850c02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-thankyou-heading&quot;)</value>
      <webElementGuid>129ac4b6-e33a-43fa-a9b9-a678a22fbbd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='fk-thankyou-heading']</value>
      <webElementGuid>ac167d36-416f-4aa1-b7cb-f165024110c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-mobile-thankyou-screen']/div/span</value>
      <webElementGuid>b3e1c55c-cdfd-44c4-9d65-101245df0fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank You for Using Our App. Hope to See you Again Soon.'])[1]/preceding::span[1]</value>
      <webElementGuid>bf72c3f7-7b58-443c-886a-1f0b15afe950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get in Touch with Us'])[1]/preceding::span[2]</value>
      <webElementGuid>21e07901-5fa3-4332-bc7b-acb9f10c47bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you!']/parent::*</value>
      <webElementGuid>6dee8468-b7f9-41ed-91b4-3dc7c80461cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span</value>
      <webElementGuid>cd62bfe1-1183-4593-96ae-5efe7d324fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'fk-thankyou-heading' and (text() = 'Thank you!' or . = 'Thank you!')]</value>
      <webElementGuid>4d953748-c538-4d60-b05e-84246da36753</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
