<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Apply button in Edit Popup</name>
   <tag></tag>
   <elementGuidId>4b48e2e0-c83b-4152-b865-6356e9d8bb83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-form-apply-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-form-apply-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56bed762-0766-4232-a838-a9e46cd70be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-form-apply-button</value>
      <webElementGuid>c3abab59-adee-4c1f-854f-36f21ef3c382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>64c5dbe9-a9ce-4aaf-a702-ba8a2639ae8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary</value>
      <webElementGuid>df966f04-f750-48cb-967a-b1f449b3c089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPLY</value>
      <webElementGuid>2506dce1-7966-4d38-9b74-625784b85b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-form-apply-button&quot;)</value>
      <webElementGuid>a2245d8b-e95e-49ab-b335-8cde5690a657</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-form-apply-button']</value>
      <webElementGuid>c1a0b16f-e742-49d4-bf8d-830ce05d1fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[2]/following::button[1]</value>
      <webElementGuid>a8e3836f-8a70-4f66-af01-e48a9ddfd951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Synopsis'])[26]/following::button[1]</value>
      <webElementGuid>2ac5d8ef-75a0-4d43-80ba-1ee98b437f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>2936692b-44ba-4b91-8973-952f7926b524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>45489092-3574-4d7a-b5fd-b8494a82eff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edit-form-apply-button' and @type = 'submit' and (text() = 'APPLY' or . = 'APPLY')]</value>
      <webElementGuid>e5804c0d-1ce4-444b-8de7-1613eecf807c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
