<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Approve Option on Response Card</name>
   <tag></tag>
   <elementGuidId>ebc7dc14-6be6-44f6-9429-7bf4e802cf3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fk-approve-action']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-approve-action</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ad632202-1cb9-41c5-878b-1020e0d96a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fk-approve-action ant-tooltip-open</value>
      <webElementGuid>041926fd-077f-4848-b844-c40111268b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-approve-action</value>
      <webElementGuid>03e62bb6-88d7-4bf1-a9ff-859e182b1502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responseCard0&quot;)/div[@class=&quot;style__MediaSectionStyled-sc-10sxs54-0 jWffer fk-card-media-section&quot;]/div[@class=&quot;style__ModerationActionsWrapper-sc-hrlvx2-1 cWbXSm fk-card-moderation-actions&quot;]/div[@id=&quot;fk-approve-action&quot;]</value>
      <webElementGuid>d5a79a66-8316-44f0-a007-d634b22db0e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fk-approve-action']</value>
      <webElementGuid>17528fd9-648b-450a-b8a0-25d6f68ee0bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responseCard0']/div/div[3]/div[2]</value>
      <webElementGuid>d866d7a1-2af8-45f1-bb5d-95aa806934f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML Audio.'])[1]/following::div[12]</value>
      <webElementGuid>45f9785b-b2c9-4e8d-a66e-02fafe2a2698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W'])[1]/following::div[32]</value>
      <webElementGuid>34437489-e0af-4a13-9f2e-e5c0b5bd9a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/preceding::div[1]</value>
      <webElementGuid>2c6ef356-d137-4648-8c5e-0e392cc03a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anonymous'])[1]/preceding::div[3]</value>
      <webElementGuid>70f418a5-a224-4341-bd2b-f572e3d600ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/div[3]/div[2]</value>
      <webElementGuid>07004602-5939-4538-bb7e-081e665d309d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'fk-approve-action']</value>
      <webElementGuid>7adb9be1-48f8-4cd2-bb6b-981c4faec1cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
