<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete confirm button NO</name>
   <tag></tag>
   <elementGuidId>365bdb91-add8-4b9b-ba3e-0aaa9d1dc8b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delete-confirm-no-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='delete-confirm-no-button']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'delete-confirm-no-button' and @type = 'button' and (text() = 'No' or . = 'No')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75f7df84-6974-455f-9903-043cb818c26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delete-confirm-no-button</value>
      <webElementGuid>7a1bc2a9-2bac-4f26-9478-9e40f2b40ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2143be4-9882-4390-80f7-d3713f53a95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default</value>
      <webElementGuid>9be45fc3-ed40-42c9-9858-869e3b8623d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>90662822-b597-4e2f-9b62-906b92690cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-confirm-no-button&quot;)</value>
      <webElementGuid>0c9365e7-aee7-4356-b22f-c8770f835320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='delete-confirm-no-button']</value>
      <webElementGuid>d69b8b11-85a6-438c-a655-356acafa6f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to delete?'])[1]/following::button[1]</value>
      <webElementGuid>3441d647-af7e-4486-98ee-2ceb258ff087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::button[1]</value>
      <webElementGuid>c23440df-b276-42f7-8eab-9e5c6eb97cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::button[1]</value>
      <webElementGuid>3f647044-d879-45b4-b5e4-385699288e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>4b48eeb3-8831-4b34-b7b0-210729ff0e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'delete-confirm-no-button' and @type = 'button' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>d78d4ddb-c083-4881-8dd0-d41bbb51cbfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
