<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dev Tag</name>
   <tag></tag>
   <elementGuidId>d6e80f9a-ab97-46f2-883a-fd4d0d82f2e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='0-0-AddingTags']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#0-0-AddingTags</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>65a3131e-6460-40b3-ba6c-51cb639ee643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__StyledTag-sc-1uvi1ss-0 eGJMEm fk-tag</value>
      <webElementGuid>f7af911a-6b16-44cc-8494-d06488575a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0-0-AddingTags</value>
      <webElementGuid>2f7bc1c1-9a80-482e-8426-ca128776cf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#AddingTags</value>
      <webElementGuid>2b43fdec-e803-4deb-8c0b-bb859d4e38f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0-0-AddingTags&quot;)</value>
      <webElementGuid>19369a65-0727-4f8b-85de-3651c3ff27d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='0-0-AddingTags']</value>
      <webElementGuid>c260d016-56f5-4b91-928c-79f77d697352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tags0']/div[2]/div</value>
      <webElementGuid>b0afe17a-ce6a-43a2-aec4-09ce832956dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[2]/following::div[2]</value>
      <webElementGuid>724f1e6c-4744-4ada-b486-fe11da5282f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is Edited'])[1]/following::div[4]</value>
      <webElementGuid>7062c661-b3dc-465b-8101-fa4ea71c35d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keywords'])[2]/preceding::div[1]</value>
      <webElementGuid>6ee8fc8e-aeb4-4e20-8b59-44558a769041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/preceding::div[2]</value>
      <webElementGuid>27ee88d1-9fab-4128-a8f5-636353cca4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='#AddingTags']/parent::*</value>
      <webElementGuid>89871d01-3436-4714-a548-b830baee26f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div</value>
      <webElementGuid>61a53070-11fd-4e46-b8cc-ef2ff0a9f047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '0-0-AddingTags' and (text() = '#AddingTags' or . = '#AddingTags')]</value>
      <webElementGuid>9ec498c2-41da-4a3a-9652-23cb60d521c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
