<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_i_sentiment-emoji</name>
   <tag></tag>
   <elementGuidId>3b8eda48-7faa-4e19-bb33-39fc5759b7ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='sentiment-emoji']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sentiment-emoji</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c2af6803-e4a0-4703-80a3-dfdf6a289a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>sentiment</value>
      <webElementGuid>58ba2af1-6357-4e29-934b-44cbee07f06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sentiment-emoji</value>
      <webElementGuid>c890bd0f-eccb-4f69-afaa-a9b0cc57a3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/admin/images/neutral.png</value>
      <webElementGuid>73fc0952-1549-4b3c-a32d-ed38aaa0be94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__Image-sc-hvy2cc-2 bJOgPk ant-tooltip-open</value>
      <webElementGuid>52e81fbf-3685-44d6-8efc-310bc4a00929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responseCard0&quot;)/div[@class=&quot;style__DetailSectionStyled-sc-3196xp-0 jvbqdr fk-card-content fk-card-detail-section&quot;]/div[@class=&quot;style__IntroWrapper-sc-hvy2cc-3 kFzxMa fk-user-wrapper&quot;]/div[@class=&quot;style__SentimentContainer-sc-hvy2cc-1 jeoLVo&quot;]/img[@id=&quot;sentiment-emoji&quot;]</value>
      <webElementGuid>c42e54e3-e92a-47ff-b829-0b01eebec70d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='sentiment-emoji']</value>
      <webElementGuid>f32c6246-f9c7-4f43-b519-f5a12b8497c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responseCard0']/div[2]/div/div[3]/img</value>
      <webElementGuid>4606ab48-fcd0-439d-9618-12b1dd11ccfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='sentiment']</value>
      <webElementGuid>f5a68b57-e932-4180-aee2-3b9824a310d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>31ab9045-a2dc-4ba3-a2c4-c5ca186844b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'sentiment' and @id = 'sentiment-emoji' and @src = '/admin/images/neutral.png']</value>
      <webElementGuid>4f4616c9-64bc-4a09-8a72-6485c1ae84f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
