<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Keywords Option on Response Card</name>
   <tag></tag>
   <elementGuidId>fa4c0a5e-15e5-4de4-b398-36edc7bef981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-keywords-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tab-keywords-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7f0fd7e-fb68-437f-8141-9a131ac82432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__TabStyled-sc-q8sp5b-0 durxTO tabs </value>
      <webElementGuid>a82ea60a-93f1-4adc-9a0b-b123cfcc3630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-keywords-0</value>
      <webElementGuid>d5aba42d-e46a-43ae-985e-bb5303f09bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keywords</value>
      <webElementGuid>df15ab4e-cf95-4250-b14e-e8cc55e6f027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-keywords-0&quot;)</value>
      <webElementGuid>4b649c2d-75a2-4eec-9b99-0c3640a7c84d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tab-keywords-0']</value>
      <webElementGuid>4adfd3b1-c327-4ad2-8a04-bb97c4284f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responseCard0']/div[2]/div[2]/div[2]</value>
      <webElementGuid>9d67a205-5661-4d22-8efe-2d4e327e6fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/following::div[1]</value>
      <webElementGuid>13b6b030-b445-4e77-b567-50102cc6ee09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share Publicly'])[1]/following::div[4]</value>
      <webElementGuid>157c3fb1-2de7-40ff-9abb-4fb7349b91ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trackers'])[1]/preceding::div[1]</value>
      <webElementGuid>d8171fee-b3c9-4b94-980b-caee29074c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>872beedf-c764-41f8-b087-321c0f08d1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tab-keywords-0' and (text() = 'Keywords' or . = 'Keywords')]</value>
      <webElementGuid>58d495e3-8d43-4a52-a0b8-a32131747ee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
