<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Name_response_card</name>
   <tag></tag>
   <elementGuidId>fb592845-b356-4b92-89cf-f44c6b6ad700</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk-user-name-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='fk-user-name-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>325720ec-366f-4e45-b2b1-2c578ec81191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fk-user-name-text</value>
      <webElementGuid>4a037fc5-9280-4324-a0de-e3408b30e22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-user-name-text</value>
      <webElementGuid>3eed98f2-3c14-4286-9fbe-a8777510d020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Waqas</value>
      <webElementGuid>dfb8da47-64e6-450e-978b-9c80145b7b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-user-name-text&quot;)</value>
      <webElementGuid>ef9f5288-3097-47f1-a629-2cb603ab621d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='fk-user-name-text']</value>
      <webElementGuid>4b3070eb-7ff9-402b-a9fd-b06c24c902e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-user-name']/h4</value>
      <webElementGuid>ab50c0f4-360a-475a-a47a-a8846c2cbaff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W'])[2]/following::h4[1]</value>
      <webElementGuid>2e46847f-36c2-42df-949a-9465402a22a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[1]/following::h4[1]</value>
      <webElementGuid>1f877b2b-eefd-427c-ab24-ac37f3b9e7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i'])[2]/preceding::h4[1]</value>
      <webElementGuid>59a157a6-0e5e-4d6a-befd-790443e30a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transcription'])[1]/preceding::h4[1]</value>
      <webElementGuid>c96eb3b0-8de1-441a-95f6-52713325c432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Waqas']/parent::*</value>
      <webElementGuid>c47ebcd1-01df-4bd8-a156-e2757cba2584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/h4</value>
      <webElementGuid>a72db5da-f26b-49b7-a497-27951fd8bb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'fk-user-name-text' and (text() = 'Waqas' or . = 'Waqas')]</value>
      <webElementGuid>823e76e8-ca11-4497-bd94-35764b9ee54b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
