<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>permission_response_card</name>
   <tag></tag>
   <elementGuidId>1e4b6b7d-051d-4825-a6a5-eefd2356b1ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk-creation-time</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='fk-creation-time']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cc9b6f09-aecd-4b99-819b-a21f48239abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fk-creation-time</value>
      <webElementGuid>f915a865-57e8-41a2-8388-3ce6da48cd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-creation-time</value>
      <webElementGuid>eb599a1d-87da-40d1-9739-9d87b71e4ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>46s | Share Publicly</value>
      <webElementGuid>c8791b56-3345-48f5-9d50-bc6bf621368f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-creation-time&quot;)</value>
      <webElementGuid>32951661-122a-4c77-9f61-dca02568c607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='fk-creation-time']</value>
      <webElementGuid>867dc4c2-a132-4590-94a2-1642339dd186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responseCard0']/div[2]/div/div[2]/span</value>
      <webElementGuid>a36510e1-31c7-4dd0-8359-902791be15fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i'])[2]/following::span[1]</value>
      <webElementGuid>90df5199-bb07-476c-bba4-8e870e840f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waqas'])[1]/following::span[2]</value>
      <webElementGuid>559060a1-a227-4178-9d79-a60f066bb590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transcription'])[1]/preceding::span[1]</value>
      <webElementGuid>f2454e0e-5e21-4627-bf29-16aa28166fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, hello, mic testing. Hello, hello, one, two, three.'])[1]/preceding::span[1]</value>
      <webElementGuid>a9084ac7-5c8e-42a1-b2e9-af802c0d0720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='46s | Share Publicly']/parent::*</value>
      <webElementGuid>63a08995-0b75-425d-9726-4deec014bc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>152a3bce-197f-4545-9e5f-13e886a11d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'fk-creation-time' and (text() = '46s | Share Publicly' or . = '46s | Share Publicly')]</value>
      <webElementGuid>9a9dcf87-cc9c-4800-a6f9-d0090bd4a97e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
