<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select sentiment negative</name>
   <tag></tag>
   <elementGuidId>b57f9177-208f-4340-854e-12cba4bcc4e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='select-sentiment-negative']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-sentiment-negative</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'select-sentiment-negative' and @title = 'Negative' and (text() = 'Negative' or . = 'Negative')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d1fed5cf-2892-4fd6-beff-82b5ab9e0ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-sentiment-negative</value>
      <webElementGuid>1ea1d63d-968b-4f64-ac34-b821e4442a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3d0b0e34-ca59-4704-a24e-eabf3330c58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item ant-select-item-option ant-select-item-option-active</value>
      <webElementGuid>ce115268-d348-446a-8b07-b706e89a2313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Negative</value>
      <webElementGuid>1e10072b-0e28-4b6d-8e9e-56111aa8466e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Negative</value>
      <webElementGuid>211a5da3-d68c-497f-b278-f742ac056077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-sentiment-negative&quot;)</value>
      <webElementGuid>cad0b124-2a8b-4c16-8a13-62c48d5a4dbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='select-sentiment-negative']</value>
      <webElementGuid>f24a9fee-287e-4871-80e8-9afe4340424a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positive'])[1]/following::div[1]</value>
      <webElementGuid>6ab67caa-5912-4391-b56b-102ca40f340a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='neutral'])[1]/following::div[7]</value>
      <webElementGuid>17eb58d0-5f7a-4fcf-a68e-ab8fefe34d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neutral'])[2]/preceding::div[2]</value>
      <webElementGuid>d97f5dc2-01af-4722-aab7-d52137c7ef5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>e197610e-d736-4bec-96e2-91c62c9e80f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'select-sentiment-negative' and @title = 'Negative' and (text() = 'Negative' or . = 'Negative')]</value>
      <webElementGuid>a63f7c6e-4fd3-4e60-b1a7-b079705fe65b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
