<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Shareable link question</name>
   <tag></tag>
   <elementGuidId>7e80991f-9f37-42eb-817f-d37be3b2d91d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='fk-question-heading']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-question-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>460eaf94-285a-4562-bbf1-14b807a42fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-question-heading</value>
      <webElementGuid>7198bf94-05be-4b57-8296-ac0569752648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__Heading-sc-1g5zts-1 avqeb</value>
      <webElementGuid>b60cafd1-3882-4ea4-b9fb-b2c154c03395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What is your opinion on the ticket pricing for PSL8 matches?</value>
      <webElementGuid>fdd5ca36-b852-4a72-8df5-2a9c79d3abf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-question-heading&quot;)</value>
      <webElementGuid>2a704877-f7f6-45c5-82be-372102de8b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='fk-question-heading']</value>
      <webElementGuid>0a8b9b95-bd42-42b5-b47c-69b3b55532dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-app']/div/div[2]/div/span[2]</value>
      <webElementGuid>ba52f193-8a0b-4522-8ee1-0747b92d3f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question'])[1]/following::span[1]</value>
      <webElementGuid>9f04e87e-fd02-4d24-a9b0-9f828d19766e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[1]/following::span[2]</value>
      <webElementGuid>160cafe1-1214-4afd-bfae-dc80e4d62d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/preceding::span[1]</value>
      <webElementGuid>0f2a6dfe-c4fb-4a2f-a1c8-f5f3d935e048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anonymous'])[1]/preceding::span[2]</value>
      <webElementGuid>51d16d93-ecb9-4e28-ae1f-738b3150f008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>84cac10f-13dc-443e-8fb0-f41b512cf51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'fk-question-heading' and (text() = 'What is your opinion on the ticket pricing for PSL8 matches?' or . = 'What is your opinion on the ticket pricing for PSL8 matches?')]</value>
      <webElementGuid>075526f3-2d8e-4be5-afc2-de5c7f8eb776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
