<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Share to LinkedIn</name>
   <tag></tag>
   <elementGuidId>6490e8e6-879b-4031-97b7-d030e1c34e00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='fk-sharing-linkedin-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-sharing-linkedin-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6f98bb2c-4656-453c-9955-ec4c429e76d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__Image-sc-czhc8e-2 gGXcBO fk-sharing-action</value>
      <webElementGuid>d16bff3a-0397-4061-ac65-05576b18ab94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-sharing-linkedin-1</value>
      <webElementGuid>e7191328-bca5-4f48-a9f3-766946d7fb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/admin/images/linkedin.png</value>
      <webElementGuid>c229d89f-0634-4def-a873-a3a32d1b8299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>fk-linkedin-icon</value>
      <webElementGuid>3521e5b4-97d7-4ee9-8c38-64cc24931978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responseCard0&quot;)/div[@class=&quot;style__Footer-sc-czhc8e-0 fxqRxp&quot;]/div[@class=&quot;style__ContentActions-sc-czhc8e-1 tTIfz fk-card-content-actions fk-social-actions&quot;]/img[@id=&quot;fk-sharing-linkedin-1&quot;]</value>
      <webElementGuid>5136b5a7-b5bc-442f-8c49-6d2bb7fe36da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='fk-sharing-linkedin-1']</value>
      <webElementGuid>9661cd6b-a87d-4bca-9861-6a08e8922fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responseCard0']/div[3]/div/img[2]</value>
      <webElementGuid>85b16f02-295a-4c31-badd-c30aa81d52cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='fk-linkedin-icon']</value>
      <webElementGuid>7c8834fa-462a-4d33-ac35-a146fbb94dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>198a18b7-e7fc-49f5-9313-63eb0814ac37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'fk-sharing-linkedin-1' and @src = '/admin/images/linkedin.png' and @alt = 'fk-linkedin-icon']</value>
      <webElementGuid>34bedd67-95fa-4ca8-a955-8434d970be95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
