<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Shareable link name</name>
   <tag></tag>
   <elementGuidId>6106c80d-4093-4c6d-bfd6-fe1c6aa7be93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='fk-post-author-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-post-author-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7fa24cd4-fa46-40c3-87ba-d79fc255de6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-post-author-name</value>
      <webElementGuid>fd141732-3480-4d51-97c7-a6a80c172c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__AuthorText-sc-1g5zts-2 cjQPTz</value>
      <webElementGuid>575a4320-169a-47f6-98f2-629cd6662f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anonymous</value>
      <webElementGuid>d0aaeb79-67c2-438c-8edf-e9ae8af84406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-post-author-name&quot;)</value>
      <webElementGuid>cc73922b-705d-4ce5-9e1e-4047b7cb3bfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='fk-post-author-name']</value>
      <webElementGuid>6768421f-93d7-4900-9b4d-e5a770b6b173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-app']/div/div[2]/div[2]/div/div[2]/span</value>
      <webElementGuid>ddcdd73c-6c66-4805-9dec-da0220e66576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/following::span[1]</value>
      <webElementGuid>1179194d-a7a5-410c-8876-1f5b33d1b753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is your opinion on the ticket pricing for PSL8 matches?'])[2]/following::span[2]</value>
      <webElementGuid>fac5856a-e997-42fd-a604-762739dd8149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keywords'])[1]/preceding::span[2]</value>
      <webElementGuid>5dda9741-451a-4a97-9326-4b8c656c0b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ticket pricing'])[1]/preceding::span[3]</value>
      <webElementGuid>b4e289f7-7813-4806-862d-c438a4f831f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anonymous']/parent::*</value>
      <webElementGuid>46815004-b4de-4581-bd38-7b33b1141831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>5b595544-58e6-4033-9162-bf99dc087bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'fk-post-author-name' and (text() = 'Anonymous' or . = 'Anonymous')]</value>
      <webElementGuid>c7f7ce14-99bc-4db7-889d-6fb4ca6dd95a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
