<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Share to twitter</name>
   <tag></tag>
   <elementGuidId>c038ac65-0e6c-46b9-9a25-d3da8c04420c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='fk-sharing-twitter-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-sharing-twitter-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3ecff73f-c26d-47aa-85ed-98843616b27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__Image-sc-czhc8e-2 gGXcBO fk-sharing-action</value>
      <webElementGuid>19ef805e-66cc-445f-8661-54cb4e4244e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-sharing-twitter-1</value>
      <webElementGuid>545105c8-4dfe-4931-93df-812f373f22f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/admin/images/twitter.png</value>
      <webElementGuid>fe5f42b7-9771-47c0-a0fe-33947650bf87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>fk-twitter-icon</value>
      <webElementGuid>8ef42516-4faa-49c1-a821-896c623a203c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responseCard0&quot;)/div[@class=&quot;style__Footer-sc-czhc8e-0 fxqRxp&quot;]/div[@class=&quot;style__ContentActions-sc-czhc8e-1 tTIfz fk-card-content-actions fk-social-actions&quot;]/img[@id=&quot;fk-sharing-twitter-1&quot;]</value>
      <webElementGuid>61e243bb-319c-4d2a-865d-b7337bb05960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='fk-sharing-twitter-1']</value>
      <webElementGuid>f0e5fdc1-c06b-4190-82dc-4ba68cb0075e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responseCard0']/div[3]/div/img</value>
      <webElementGuid>7c125beb-7ffd-411b-98a3-75f7af6163c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='fk-twitter-icon']</value>
      <webElementGuid>3aad13c1-0565-4558-b477-60f80eff8a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>42e52b6c-b3f9-4391-8576-ffb9602e9caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'fk-sharing-twitter-1' and @src = '/admin/images/twitter.png' and @alt = 'fk-twitter-icon']</value>
      <webElementGuid>f0363146-da59-41cb-a6d8-83e3b4d04022</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
