<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Synopsis input field</name>
   <tag></tag>
   <elementGuidId>dbaea0db-a8b1-4864-8068-4ffb75ed6d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='synopsis-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#synopsis-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7684bbba-dec4-4fa6-ad3c-9b37a7c48670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>synopsis-input</value>
      <webElementGuid>d61b1d50-4da0-466c-bf6b-10e8c8f270c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3ece3d4-ade2-40e4-9c19-c644733e16ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm ant-input-borderless tags-input</value>
      <webElementGuid>df6ca0ea-ba6f-42bb-8464-4cc8292fec24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add synopsis</value>
      <webElementGuid>13824cd4-68cd-4fdf-8513-f1a90cdd6c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;synopsis-input&quot;)</value>
      <webElementGuid>a27822ce-265a-4511-b6a5-32d34dc4f8f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='synopsis-input']</value>
      <webElementGuid>9e9426ac-5a27-4b35-98bc-29fdc619c2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>d9a76425-8e22-40be-ae04-7fb6a9bbb0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'synopsis-input' and @type = 'text' and @placeholder = 'Add synopsis']</value>
      <webElementGuid>4837ce79-1912-4fcb-addf-bee44919d564</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
