<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tags input field</name>
   <tag></tag>
   <elementGuidId>3d621cf8-fa59-47e3-a3ff-7eeedcf907c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tags-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tags-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c375830-3713-4e3a-be99-09a8ec97866f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tags-input</value>
      <webElementGuid>f175bc7b-cd2c-4bc8-9291-bfedb494e6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91834a9f-90ce-4466-8ca9-0a6400e5f33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm ant-input-borderless tags-input</value>
      <webElementGuid>2369b38d-5aa7-4ab2-812a-e9e9d04e4e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add tag</value>
      <webElementGuid>9c57d256-677e-408e-827e-c2972ac4dc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tags-input&quot;)</value>
      <webElementGuid>0119f30e-0a25-4c0f-bc68-d0ac7feb14d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tags-input']</value>
      <webElementGuid>d0790622-639a-4a1c-a663-37ef17ffda30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6b08258c-223f-42df-9a7e-02d0d6a9fc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tags-input' and @type = 'text' and @placeholder = 'Add tag']</value>
      <webElementGuid>5e154148-9687-464f-a9e6-f90fa955f806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
