<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tags Option On Response Card</name>
   <tag></tag>
   <elementGuidId>06bc6865-5b9c-4078-bd56-8f4d4fa63681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-tags-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tab-tags-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>412c3200-d51f-4116-8722-96b972b5621d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__TabStyled-sc-q8sp5b-0 durxTO tabs </value>
      <webElementGuid>df4628a4-5a2e-4574-b397-b6d52183cde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-tags-0</value>
      <webElementGuid>d7351791-8f13-4d9a-8f0b-9adcb65e147b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tags</value>
      <webElementGuid>a96c562d-d332-4f86-967a-1a672407bdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-tags-0&quot;)</value>
      <webElementGuid>f67f5cd6-bd4f-465e-9053-4d114648bc34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tab-tags-0']</value>
      <webElementGuid>17f995d5-8fee-469c-9779-88892f53d1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responseCard0']/div[2]/div[2]/div</value>
      <webElementGuid>0a16f9db-b3cb-433a-8c5f-c80073780e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share Publicly'])[1]/following::div[3]</value>
      <webElementGuid>79443097-5f1f-49f4-8d31-a6dbd58d5536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::div[3]</value>
      <webElementGuid>697d178d-d867-4c0b-ab86-ab83e4fad5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keywords'])[1]/preceding::div[1]</value>
      <webElementGuid>d8f51372-0caa-4713-a4b4-ba9e81bbf671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div</value>
      <webElementGuid>eb11e0bf-cdda-4d04-a745-5454216cf75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tab-tags-0' and (text() = 'Tags' or . = 'Tags')]</value>
      <webElementGuid>4c1ed96a-d2d6-4902-8c66-bae4c2466593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
