<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Trackers Option on esponse Card</name>
   <tag></tag>
   <elementGuidId>1a1ed7a6-3f61-4c83-a7d3-9fb5bdcc6e50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-trackers-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tab-trackers-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47861e90-c697-4258-8b4f-8b26ef099eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__TabStyled-sc-q8sp5b-0 durxTO tabs </value>
      <webElementGuid>034b967c-941c-42a2-8c98-aac842cd63db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-trackers-0</value>
      <webElementGuid>26fbfd88-4f40-46fc-b212-ba9605abec63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trackers</value>
      <webElementGuid>5eb9a0b3-212a-4c68-8582-49b60a51b09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-trackers-0&quot;)</value>
      <webElementGuid>5119bd0e-6b9d-475e-b0c5-deef0ac5b2b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tab-trackers-0']</value>
      <webElementGuid>848f2c43-9c5c-429c-8de4-c41bd89f96eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responseCard0']/div[2]/div[2]/div[3]</value>
      <webElementGuid>7ac1eb36-eca6-410e-afee-33950c23f283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keywords'])[1]/following::div[1]</value>
      <webElementGuid>7b15d8bd-5ffa-4b94-ba41-4b79b661ed6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/following::div[2]</value>
      <webElementGuid>55d6214d-faa5-4997-8e55-e883c9dd69d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transcription'])[1]/preceding::div[2]</value>
      <webElementGuid>edeb6561-6f65-4911-b927-89ca97da9c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div[3]</value>
      <webElementGuid>1940e915-0016-4f9b-9eea-45d20730873d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tab-trackers-0' and (text() = 'Trackers' or . = 'Trackers')]</value>
      <webElementGuid>2254a35c-054d-4572-bf5c-fb87dc69c395</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
