<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Transcription Text input</name>
   <tag></tag>
   <elementGuidId>bf439a83-8cad-4620-a632-d3ef53257e93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='transcribed-text-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transcribed-text-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>61f8d33b-733d-47aa-b36c-f97558a87804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1ef137cc-0d75-4a68-9874-6da49e614d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transcribedText</value>
      <webElementGuid>c93ae140-db75-40d2-bfa8-8320657ccaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transcribed-text-input</value>
      <webElementGuid>97e023cd-0d39-4db9-b8c8-ccf217b73e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Transcribed Text</value>
      <webElementGuid>8cdaf042-d790-4096-9e05-eb5968a9e0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>1c282be4-1308-4a5f-aa6e-6b1ed5b98f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Question 2, long video. Just to see if that issue still persists, if we upload a long video then Google bucket API call goes later than the API for the post. So the posts are being created first and then Google storage is being created. So that's why we're getting that, is why we were getting the error. Let's see.</value>
      <webElementGuid>d624f660-cbe8-4719-8596-94a7af765f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transcribed-text-input&quot;)</value>
      <webElementGuid>18d14ebc-e6d2-4a42-b0b0-66b70fe4335e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='transcribed-text-input']</value>
      <webElementGuid>9ab33e40-4629-4305-91ca-7d98062bb784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transcribed Text'])[1]/following::textarea[1]</value>
      <webElementGuid>ec4c40cb-4f70-4bfe-bc6c-00e659f3f7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[13]/following::textarea[1]</value>
      <webElementGuid>789c0046-e918-42a1-a294-587416d46c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sentiment'])[1]/preceding::textarea[1]</value>
      <webElementGuid>9c9b4836-29e7-4dc8-97b8-18ff9d49f3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neutral'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b46211ad-ed3d-4588-b126-8eafd6f51d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7e925a80-ecbf-436e-93be-2d8edd1c26c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'transcribedText' and @id = 'transcribed-text-input' and @placeholder = 'Add Transcribed Text' and (text() = concat(&quot;Question 2, long video. Just to see if that issue still persists, if we upload a long video then Google bucket API call goes later than the API for the post. So the posts are being created first and then Google storage is being created. So that&quot; , &quot;'&quot; , &quot;s why we&quot; , &quot;'&quot; , &quot;re getting that, is why we were getting the error. Let&quot; , &quot;'&quot; , &quot;s see.&quot;) or . = concat(&quot;Question 2, long video. Just to see if that issue still persists, if we upload a long video then Google bucket API call goes later than the API for the post. So the posts are being created first and then Google storage is being created. So that&quot; , &quot;'&quot; , &quot;s why we&quot; , &quot;'&quot; , &quot;re getting that, is why we were getting the error. Let&quot; , &quot;'&quot; , &quot;s see.&quot;))]</value>
      <webElementGuid>5602ba4f-1d63-417d-bfff-75b626ff1835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
