<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User Name on Card</name>
   <tag></tag>
   <elementGuidId>f3c62354-6842-498d-9921-4103422dec3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='fk-user-name-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-user-name-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>5801e89b-c4f0-4461-a912-e3c3badab181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fk-user-name-text</value>
      <webElementGuid>965967b1-40b7-4a1c-baab-c2c1108fc6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-user-name-text</value>
      <webElementGuid>a2797c51-b4a5-4310-a335-bda8e737b930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anonymous</value>
      <webElementGuid>8e9707d0-f729-4bd9-9d07-26fbc078544b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responseCard0&quot;)/div[@class=&quot;style__DetailSectionStyled-sc-3196xp-0 jvbqdr fk-card-content fk-card-detail-section&quot;]/div[@class=&quot;style__IntroWrapper-sc-hvy2cc-3 kFzxMa fk-user-wrapper&quot;]/div[@class=&quot;style__TextContainer-sc-hvy2cc-0 gxQttY fk-user-meta&quot;]/div[@id=&quot;fk-user-name&quot;]/h4[@id=&quot;fk-user-name-text&quot;]</value>
      <webElementGuid>842405ac-8b03-4c3a-ab7b-25ffd517b87c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='fk-user-name-text']</value>
      <webElementGuid>500f1b14-1df5-4e6d-afe7-d2c5fa69fe53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-user-name']/h4</value>
      <webElementGuid>4bebcbf0-5b49-4d1a-9304-efa26eecc602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/following::h4[1]</value>
      <webElementGuid>114ac06e-6bd6-42c9-82fb-4dd37ac1ff2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[1]/following::h4[1]</value>
      <webElementGuid>4061c7ae-0b5b-42a4-8c4a-6e58c350528d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i'])[1]/preceding::h4[1]</value>
      <webElementGuid>1c9963ba-b473-4df1-8cd5-058f0721d8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/preceding::h4[1]</value>
      <webElementGuid>dd6ec40a-b632-49f5-a965-4929e72daa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anonymous']/parent::*</value>
      <webElementGuid>1eb2c109-5e93-4705-a03b-9e8c1635bb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div[2]/div/h4</value>
      <webElementGuid>10c4fb41-745c-4ee4-b284-16e6cd04d606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'fk-user-name-text' and (text() = 'Anonymous' or . = 'Anonymous')]</value>
      <webElementGuid>66c9615f-45d3-4848-87e0-6312c990ed60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
