<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Video play icon on card</name>
   <tag></tag>
   <elementGuidId>5e901247-0172-435a-a4c6-ac2a2d0b7444</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='fk-card-media-wrapper']/div/div/div/div/div/div/div/div[2])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.fk-video-play-pause-action</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f8aad4d-1b28-4905-81b0-e25daf89d84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fk-video-play-pause-action</value>
      <webElementGuid>244d2d44-81ad-466a-8c57-6492d5a8999f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responseCard5&quot;)/div[@class=&quot;style__MediaSectionStyled-sc-10sxs54-0 jWffer fk-card-media-section&quot;]/div[@id=&quot;fk-card-media-wrapper&quot;]/div[@class=&quot;slick-slider fk-content-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@class=&quot;style__VideoPlayerStyled-sc-1i3pd2e-0 xAcxQ fk-video-player-container&quot;]/div[@class=&quot;fk-video-overlay&quot;]/div[@class=&quot;fk-video-play-pause-action&quot;]</value>
      <webElementGuid>212a1753-34e8-4b7b-a3c7-5a11e4359d9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='fk-card-media-wrapper']/div/div/div/div/div/div/div/div[2])[6]</value>
      <webElementGuid>87f27b83-ec39-4a89-bf45-a03487c70593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[1]/following::div[3]</value>
      <webElementGuid>844a6650-f5ce-4842-bb63-fd30db86f2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test 1 2 3'])[1]/following::div[21]</value>
      <webElementGuid>e26816e0-1f72-410e-beef-7ce8b06264bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[3]/preceding::div[9]</value>
      <webElementGuid>70b3dddc-c957-4aac-ae29-525910a9bd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anonymous'])[3]/preceding::div[11]</value>
      <webElementGuid>1eafba66-0a58-41e9-8ae5-90563e2860d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>2b2ca1bb-605c-46a2-b091-a0830674fdc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
