<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>View all responses link</name>
   <tag></tag>
   <elementGuidId>4105f3b4-80a0-4641-a708-961418bba2f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#view-all-responses-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='view-all-responses-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a7e23466-138a-4400-82c5-92a500df5b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__TextWrapper-sc-1pnycc7-0 fIZgUh regular-font</value>
      <webElementGuid>3b34bba2-919a-475b-a5d3-0f4113e5f799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>view-all-responses-button</value>
      <webElementGuid>66d287cb-29fc-45a6-ac9e-676dc3c4f70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Responses</value>
      <webElementGuid>a5592d70-dc4c-42fb-b637-ae4cb48f38fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view-all-responses-button&quot;)</value>
      <webElementGuid>285e64ea-1473-495f-aec5-9aadfe75f6cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='view-all-responses-button']</value>
      <webElementGuid>cecf7220-0efa-4e6a-ab01-824f784cfd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/p[2]</value>
      <webElementGuid>0988c39e-13f2-441a-a62d-64a334a2071d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audio'])[1]/following::p[2]</value>
      <webElementGuid>064bb38e-3a80-43db-83d1-00b44f6cded2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video'])[1]/following::p[2]</value>
      <webElementGuid>82264d35-936f-40ab-9f9b-9c012ed588b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[1]/preceding::p[1]</value>
      <webElementGuid>4f907c54-2e7c-4423-b529-393a9e4b1dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W'])[2]/preceding::p[3]</value>
      <webElementGuid>31da2f90-1a23-4722-a252-c9aa788fbdb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Responses']/parent::*</value>
      <webElementGuid>3d5d126f-00c9-4eeb-97d9-d6f4a1a38f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p[2]</value>
      <webElementGuid>1d089d6a-48c2-477f-bcf4-da0012c3e85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'view-all-responses-button' and (text() = 'View Responses' or . = 'View Responses')]</value>
      <webElementGuid>490efd0f-7b8c-4367-98b3-4059fa3331e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
