<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Organization_logo</name>
   <tag></tag>
   <elementGuidId>7796f1fc-8c27-4b50-8e2c-4c34667bc12a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4e206f0b-ba36-41b2-a3cb-705029d5e382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>9db96c12-684e-4f54-9f4f-2a616ef7995e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/admin/images/logo.png</value>
      <webElementGuid>07ea126d-1459-4332-aa66-5138107eddf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>copmany-logo</value>
      <webElementGuid>cd1bbf0a-152c-4786-bb06-e46e0f2ba327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;style__DashboardStyle-sc-1265zxf-0 hpOElW&quot;]/div[@class=&quot;style__HeaderStyled-sc-1441c0w-0 dBchoU&quot;]/div[@class=&quot;style__Avatarcontainer-sc-1441c0w-1 bSmOfj&quot;]/div[@class=&quot;logo-wrapper&quot;]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>6b5f5cd6-9fef-46d2-8bf8-13633ea16f53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/img</value>
      <webElementGuid>11bce34d-630a-4c39-9477-9f7aaf03764e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='copmany-logo']</value>
      <webElementGuid>c676d57e-43ec-4eac-936e-f40ba2be3e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f1d8be98-58d4-481e-88e4-5602ea9e033e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/admin/images/logo.png' and @alt = 'copmany-logo']</value>
      <webElementGuid>a25b90a5-8e57-4205-b36b-b803a0078832</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
