<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tags_tags-input</name>
   <tag></tag>
   <elementGuidId>c11297ef-e220-4012-bdbc-596eed808a74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tags-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tags-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f10c35c8-b5df-4ac8-941d-0a7510631bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tags-input</value>
      <webElementGuid>1c7a0323-e84d-4660-8c87-6d99a1d6707c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e54fba1-0f48-4bac-a943-bd92b613a6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm ant-input-borderless tags-input</value>
      <webElementGuid>44789856-2648-42a2-af59-1e6aa8371dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add tag</value>
      <webElementGuid>4d5e1710-2883-463a-9cd0-66c8bdf8d3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tags-input&quot;)</value>
      <webElementGuid>dac63e1b-0719-4c5e-907c-9f2b908a2559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tags-input']</value>
      <webElementGuid>9fac64c6-58c5-44db-a897-de2192b96202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>bd8c7a62-27a5-4603-b556-1b76ff17f04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tags-input' and @type = 'text' and @placeholder = 'Add tag']</value>
      <webElementGuid>675b64da-cf84-4e3f-b1cd-2f4de9a36d0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
