<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>ec8dc5ed-75e5-4ea1-94db-8d77f7a34950</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[2]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.fk-content-action.fk-content-edit-action > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>ddeb23a1-4aae-4197-a2df-d2fb622da1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>45d2e284-dfee-4060-b2be-8b96c7055af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16.97</value>
      <webElementGuid>7483b40a-766e-4fe2-8c1f-0ac0c4f36f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16.971</value>
      <webElementGuid>3d309a59-ad50-411f-8516-852d809a9482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16.97 16.971</value>
      <webElementGuid>d892c844-3a05-40bb-b7b9-56dc615e9b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responseCard0&quot;)/div[@class=&quot;style__Footer-sc-1eu4ljs-16 bifRtN&quot;]/div[@class=&quot;style__ContentActions-sc-1eu4ljs-17 dLDKsq fk-card-content-actions fk-content-actions&quot;]/div[@class=&quot;fk-content-action fk-content-edit-action&quot;]/svg[1]</value>
      <webElementGuid>484efba3-4e23-4b08-898b-a77f6f2a90ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>82d55e59-7405-45c6-9818-9d288f480f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trackers'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>2bfd08ee-92cf-4a5c-932b-68453fda17af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>635d147b-8ad8-4ced-9cd9-5555873ba8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W'])[2]/preceding::*[name()='svg'][7]</value>
      <webElementGuid>3b218d04-2629-4c77-8d3d-45c738d6d2d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
