<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Transcribed Text</name>
   <tag></tag>
   <elementGuidId>d4586913-07f9-45f7-94bf-074a1015007c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='transcribed-text-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transcribed-text-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5c8698a3-777b-44b0-a239-92fa1b01c8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>843185f3-4647-4132-9755-3a20a49bd0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transcribedText</value>
      <webElementGuid>d454b8ee-88f0-4a33-bb6e-4b67fd2fc7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transcribed-text-input</value>
      <webElementGuid>eaeaa3ec-41f7-4766-a04d-4356f6494405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Transcribed Text</value>
      <webElementGuid>9b3ec181-8387-4979-8520-f36db7f4b00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>5f00f5d6-61b5-4a91-9e0f-fe0e787fab9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello, this is audio. Testing, question number one for testing start to party movie. Customer quality assurance engineer testing the way. This is Edited</value>
      <webElementGuid>0d97e69d-4a7f-4b2c-ae52-80bfc24818aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transcribed-text-input&quot;)</value>
      <webElementGuid>66da0016-8f70-4766-b538-9dc39a25e543</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='transcribed-text-input']</value>
      <webElementGuid>7cd5fd17-2a1f-48d7-bad2-20f29a7db1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transcribed Text'])[1]/following::textarea[1]</value>
      <webElementGuid>978ae46d-7307-44bb-8787-1804fed935a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::textarea[1]</value>
      <webElementGuid>3d70a2bc-b773-4810-8fb6-70546138d48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sentiment'])[1]/preceding::textarea[1]</value>
      <webElementGuid>dd31c226-17b9-47f1-ac4a-4df26150e94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neutral'])[1]/preceding::textarea[1]</value>
      <webElementGuid>7b4e4816-5a4c-45a9-9bdb-216d6e53dbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>48564bd2-0f6d-452d-977e-a21f204d26f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'transcribedText' and @id = 'transcribed-text-input' and @placeholder = 'Add Transcribed Text' and (text() = 'Hello, this is audio. Testing, question number one for testing start to party movie. Customer quality assurance engineer testing the way. This is Edited' or . = 'Hello, this is audio. Testing, question number one for testing start to party movie. Customer quality assurance engineer testing the way. This is Edited')]</value>
      <webElementGuid>1a98841d-e035-4066-a543-d2728d877b12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
