<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Preview Campaign</name>
   <tag></tag>
   <elementGuidId>75f65d8d-794f-4837-8bc9-d9ae25c34755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ed042d4-6023-481e-9d39-afece95074c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>b0e7bd8a-c94a-413d-bcc6-0c8963b354d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>37b63d65-b817-406b-a701-9346694d0677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://dev.ccapps.fankave.com/cisco/feedback/testfanvoiceid</value>
      <webElementGuid>7f2e6b36-b1ea-42fd-923c-4bca6aeab311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview Campaign</value>
      <webElementGuid>e9b2944b-c068-471c-9029-2db504e26807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;style__DashboardStyle-sc-1265zxf-0 hpOElW&quot;]/div[@class=&quot;sharedStyles__DashboardMainContainerStyle-sc-67rum6-6 fQHQWc&quot;]/div[2]/div[@class=&quot;sharedStyles__DashboardMainContainerStyle-sc-67rum6-6 fQHQWc&quot;]/div[@class=&quot;sharedStyle__ThankyouContainer-sc-tx8g94-10 dOBnAS&quot;]/div[@class=&quot;thankyou-screen&quot;]/div[@class=&quot;sharedStyle__ButtonDiv-sc-tx8g94-13 hRWfFd&quot;]/div[@class=&quot;style__BorderedButton-sc-1hf2caz-2 hXFcMz&quot;]/a[1]</value>
      <webElementGuid>af946841-0de5-4604-ae0c-b5ae9fd3d99d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[2]/div/a</value>
      <webElementGuid>3dbaf3f5-7b86-400e-8cc4-b9fb1384496c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Preview Campaign')]</value>
      <webElementGuid>d98bfc1d-33f4-4e9c-bc74-6cb80cfc48c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Go to Campaign', &quot;'&quot;, 's Page')])[1]/following::a[1]</value>
      <webElementGuid>b1f43aee-51d0-4fab-81e7-f745e4964aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video'])[1]/following::a[1]</value>
      <webElementGuid>8c78aedc-93fe-401d-a71f-08fd1f276207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Preview Campaign']/parent::*</value>
      <webElementGuid>7f07587a-2cc9-476d-ab4c-33150569d29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://dev.ccapps.fankave.com/cisco/feedback/testfanvoiceid']</value>
      <webElementGuid>07b7353e-e4ea-4c82-90ce-c48f195c4080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>1e7a3a90-27c7-4342-90ba-9ce077c80b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://dev.ccapps.fankave.com/cisco/feedback/testfanvoiceid' and (text() = 'Preview Campaign' or . = 'Preview Campaign')]</value>
      <webElementGuid>e6b2941f-4bab-4f36-b2d8-2956e30f677b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
