<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Approve</name>
   <tag></tag>
   <elementGuidId>910bbc1f-8bfe-4231-96e5-bc0b9a99ca37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk-approve-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fk-approve-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f10ccba2-19cd-493f-9c78-95ff75bbcadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>common__SecondaryButton-sc-khnafi-1 kDUegO fk-secondary-button fk-approve-button</value>
      <webElementGuid>d5f16059-e8a8-4a8a-b175-a4961cfacdf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-approve-button</value>
      <webElementGuid>516b1d89-87cb-4854-b02b-f166b1e21ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>80e1df16-413c-4d85-a8bf-b57e1cbfadaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-approve-button&quot;)</value>
      <webElementGuid>1be7ce9a-e814-4c4f-b6d3-7840d4758879</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fk-approve-button']</value>
      <webElementGuid>9b8daf9e-4a83-4eed-9bf6-01dcadf95bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-video-player-container']/div/div[4]/button</value>
      <webElementGuid>cae358f2-863c-409d-bda4-2d3dfb847202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is Question 01 for Testing?'])[1]/following::button[1]</value>
      <webElementGuid>64f83bca-5ad7-46aa-94f0-8ea119beabba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[1]/following::button[1]</value>
      <webElementGuid>e827704d-15d8-498f-b0c6-d01ce84bb080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rerecord'])[1]/preceding::button[1]</value>
      <webElementGuid>1c20c131-0b8a-4963-b80f-ed57816ea55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8b893f5d-6f82-4682-a8a4-f6db39c2e9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fk-approve-button' and (text() = 'Approve' or . = 'Approve')]</value>
      <webElementGuid>9869db3b-ecea-44cb-93a6-9021fa0211c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
