<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>6a142ac7-b8b3-4882-b928-e1a726b0c594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk-submit-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fk-submit-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ebab78f-c9a0-4180-bbdc-fbed2dd16f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-submit-btn</value>
      <webElementGuid>789bdce9-d0ac-4a9f-ad38-f18902045777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>common__PrimaryButton-sc-khnafi-0 gicccN fk-submit-btn</value>
      <webElementGuid>d7eb7e98-46df-4c17-b697-cf74c2bf9232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>c30bd4d3-e534-42a1-980b-42a2408e9621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-submit-btn&quot;)</value>
      <webElementGuid>d9ba0388-ebc9-48ac-9a3a-dfd68a207957</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fk-submit-btn']</value>
      <webElementGuid>1f6335f5-7564-456c-a101-99e77c554e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-dktp-thankyou-screen']/form/button</value>
      <webElementGuid>8087e567-c1b0-4430-929d-f7afdfb9d4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get in Touch'])[1]/following::button[1]</value>
      <webElementGuid>b180f201-f5a4-40de-a369-5a56aa8574ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you!'])[1]/following::button[1]</value>
      <webElementGuid>97a851a0-cd4d-4828-a60e-10adede1a528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'fk-submit-btn', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>7fba0ede-bcc6-439a-aa44-fb40f7637fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>404ddb73-8bc1-4384-b6fd-fc434468d24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9bc84336-19dc-483e-9473-96a3f24f180b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fk-submit-btn' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>51743f85-c5b0-4f4c-a09b-a26ded2c9877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
