<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Organization_logo</name>
   <tag></tag>
   <elementGuidId>fd655974-1e58-41f3-a9c1-5f63ee8707c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ff9e20b0-b866-4726-9a73-9535ec0c6143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>484553d6-e673-480d-bc19-15fcb7ee9500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/admin/images/logo.png</value>
      <webElementGuid>42c0c5f8-a31a-4db9-a5d8-278f733e5c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>copmany-logo</value>
      <webElementGuid>6d4e95de-b057-4106-b69d-f83c80c30fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;style__DashboardStyle-sc-1265zxf-0 hpOElW&quot;]/div[@class=&quot;style__HeaderStyled-sc-1441c0w-0 dBchoU&quot;]/div[@class=&quot;style__Avatarcontainer-sc-1441c0w-1 bSmOfj&quot;]/div[@class=&quot;logo-wrapper&quot;]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>0810e6a2-c4f5-4374-8046-bf5a831a1362</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/img</value>
      <webElementGuid>30c2beed-5e7e-4909-a069-3480f445b028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='copmany-logo']</value>
      <webElementGuid>39723fe9-a79d-4fb2-b564-f0d7d0c08fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a9db4e6a-06cd-469e-b41c-582c0a16684e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/admin/images/logo.png' and @alt = 'copmany-logo']</value>
      <webElementGuid>d55b2dd1-7116-4bff-b8e5-6bdcc34226e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
