<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Get in Touch_name</name>
   <tag></tag>
   <elementGuidId>90e76250-31af-42d0-bc3e-6432c91fa367</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fk-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47129d39-6701-4726-9293-b7f6c6ed49e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>dfe4ef9a-e90d-4869-a75c-1d3a7e8c9dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name (optional)</value>
      <webElementGuid>2a34717d-0351-41b5-b110-7282063757e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fk-input fk-name </value>
      <webElementGuid>9913910b-bde0-476f-bb42-dc40ab18ac9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-name</value>
      <webElementGuid>3972a338-1ceb-4e7c-be57-c65b00c49ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>749c3cc2-9bd8-4538-bad7-6f5f85562adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f5eca11-9adc-404a-b42f-2bdc9c22f25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-name&quot;)</value>
      <webElementGuid>373d1677-f2d7-4369-a4d7-c49822b6338f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fk-name']</value>
      <webElementGuid>6afbea6d-b7db-4fe1-baac-bb65a8252b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-dktp-thankyou-screen']/form/div/input</value>
      <webElementGuid>b7dca31a-2128-45c4-ad9a-a45cf1e09046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c50c99eb-97a5-4e96-a659-977f65576373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'name' and @placeholder = 'Name (optional)' and @id = 'fk-name' and @type = 'text']</value>
      <webElementGuid>6a0fbbb8-acaa-4ecd-8f8b-7cd39dca0113</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
