<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect (1)</name>
   <tag></tag>
   <elementGuidId>77d60388-e8bb-45bf-ac35-4f48da0c7a0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>rect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>acc86db5-de8f-4eb2-b40b-513f093529a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>7b7a534f-78e5-4d5e-ab3d-ec52532e43be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a47fc97d-ac9d-406d-bf43-2df378b9ee96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>41ea702d-9d7b-42d5-b340-36e39c829c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>855a1446-69a6-4745-b53b-fcfd3c1a27be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>32d9c06c-bc8f-4412-8ee6-b3b287a066b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#ff6161</value>
      <webElementGuid>3efcc1c5-a664-48da-85c9-e18311428667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-audio-stop-record-icon&quot;)/svg[1]/rect[1]</value>
      <webElementGuid>de12bf7c-59ef-47f7-a926-07512a858e88</webElementGuid>
   </webElementProperties>
</WebElementEntity>
