<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thanks for providing your details</name>
   <tag></tag>
   <elementGuidId>10f86a0d-c131-40dc-88ee-ca0fd284646e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.style__BrandSubHeading-sc-hb79k5-3.style__EmailMessage-sc-1991k12-6.gxKsKv.bcsWVA.fk-email-confimation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fk-dktp-thankyou-screen']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2cc1f30a-15b4-445f-a59f-e9e3a9f31a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__BrandSubHeading-sc-hb79k5-3 style__EmailMessage-sc-1991k12-6 gxKsKv bcsWVA fk-email-confimation</value>
      <webElementGuid>f24a686c-c2db-45ab-88f3-7ecaeea82235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanks for providing your details!</value>
      <webElementGuid>49d732aa-cc06-4ab7-92d8-a0af803d68ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-dktp-thankyou-screen&quot;)/span[@class=&quot;style__BrandSubHeading-sc-hb79k5-3 style__EmailMessage-sc-1991k12-6 gxKsKv bcsWVA fk-email-confimation&quot;]</value>
      <webElementGuid>e91212ac-6de0-48d7-be85-e39cefda6ba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-dktp-thankyou-screen']/span[2]</value>
      <webElementGuid>413e0e1f-8a64-4f33-8817-c87e5185b41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you!'])[1]/following::span[1]</value>
      <webElementGuid>28d82eb2-c68b-4f0a-a48e-2c271257cfe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Again'])[1]/preceding::span[1]</value>
      <webElementGuid>add45081-ece4-4249-bd7f-1db5d74dc7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thanks for providing your details!']/parent::*</value>
      <webElementGuid>9ead6dd2-99ec-419e-aeab-ea58a65bfb4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>16f10185-3961-4766-8aa0-17cc216e8e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Thanks for providing your details!' or . = 'Thanks for providing your details!')]</value>
      <webElementGuid>db1966ba-80d3-4af7-afeb-1e39a742f833</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
