<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Audio responses percentage</name>
   <tag></tag>
   <elementGuidId>f7211062-33cc-4b7c-87d1-334f9f4f613b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#metrics-bar-Audio-percentage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='metrics-bar-Audio-percentage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4f33925-cb8d-4d24-82dc-288375530e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>percentage</value>
      <webElementGuid>e3a7e1d0-1468-4c73-bd10-b2f1e6a2bc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>metrics-bar-Audio-percentage</value>
      <webElementGuid>15394b18-f6aa-44da-9d3c-645d01e43a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>35%</value>
      <webElementGuid>248da140-dd7d-43bf-b03c-205446e42b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metrics-bar-Audio-percentage&quot;)</value>
      <webElementGuid>dd96c380-3e82-4c40-8c32-7f9186919272</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='metrics-bar-Audio-percentage']</value>
      <webElementGuid>eb4856c4-0b9d-44f0-9792-5440a4a62d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div[6]/div/div[2]</value>
      <webElementGuid>507ebac6-8db1-4074-9f77-ad097a060f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video'])[1]/following::div[4]</value>
      <webElementGuid>310cbb96-b9d7-43b2-bdef-9535b4098cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responses'])[2]/following::div[9]</value>
      <webElementGuid>1b3c35f5-87df-46e4-923a-983646ca33ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audio'])[1]/preceding::div[1]</value>
      <webElementGuid>ca869a4b-7dbb-4751-80ab-050d776d6b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUESTIONS'])[1]/preceding::div[2]</value>
      <webElementGuid>9248d470-1a9e-4682-93f2-41c16969f015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='35']/parent::*</value>
      <webElementGuid>e1de8ee9-2696-482c-bfd3-34b99f3fe7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[6]/div/div[2]</value>
      <webElementGuid>a6a9957f-80a7-4884-a38a-9847c7bb3640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'metrics-bar-Audio-percentage' and (text() = '35%' or . = '35%')]</value>
      <webElementGuid>9130506c-b17e-4ea8-a72e-0fb0c4ad5e67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
