<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Total Video responses</name>
   <tag></tag>
   <elementGuidId>0676a1ce-b8fc-4e8e-bf86-631854c165cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#metrics-bar-Video-count</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='metrics-bar-Video-count']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aaece28d-53a6-49b3-bd3a-a9967ca96ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>634eb4b1-1aa6-47af-a955-a4455fe11ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>metrics-bar-Video-count</value>
      <webElementGuid>6e26070d-ee01-46ad-9580-7a6ade3593c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>a7eb0642-31b3-4f67-a662-534716fa375f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metrics-bar-Video-count&quot;)</value>
      <webElementGuid>910d7799-479c-4e3c-9209-d89fdef08b02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='metrics-bar-Video-count']</value>
      <webElementGuid>f629c8e0-df7d-48e0-85f1-5ba851cc3a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div[5]/div/div</value>
      <webElementGuid>0a4b3258-6a20-4f74-88d6-19e864b2607a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responses'])[2]/following::div[3]</value>
      <webElementGuid>7ac6b1fb-2275-49fa-bd1c-a032e23274ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participants'])[2]/following::div[7]</value>
      <webElementGuid>1c388907-b4b2-4202-95ab-a8c6e3484f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video'])[1]/preceding::div[2]</value>
      <webElementGuid>10be9555-46fc-4b91-b618-22a7c6cae9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audio'])[1]/preceding::div[6]</value>
      <webElementGuid>23509030-41d6-495c-a523-5205bd3c0173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24']/parent::*</value>
      <webElementGuid>cdaec49e-1c1b-4462-9f2f-8ff95bd18e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[5]/div/div</value>
      <webElementGuid>89f8d282-5bf5-4809-94da-8a2e06b51c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'metrics-bar-Video-count' and (text() = '24' or . = '24')]</value>
      <webElementGuid>e16ff20f-9587-4b05-893a-92817dfa94f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
