<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Total questions</name>
   <tag></tag>
   <elementGuidId>5160481e-71f9-4a8c-a299-9416fc05ff52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#metrics-bar-Questions-count</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='metrics-bar-Questions-count']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5f75422-e578-442f-bc9f-63b11a7a8eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>823e1d52-36ae-4deb-95d2-24655296ac32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>metrics-bar-Questions-count</value>
      <webElementGuid>d3bc16b5-fcd2-4d56-b24a-2228b53c7cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4639dd32-3685-4261-b751-9ffbb7966d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metrics-bar-Questions-count&quot;)</value>
      <webElementGuid>a2a50d10-f19b-4178-9fb3-8be7d00ddf36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='metrics-bar-Questions-count']</value>
      <webElementGuid>29b84df9-2e7c-4fe2-a9b1-ff046c1712d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>3f653dae-ead3-4420-9403-6fdc971d78af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sentiment'])[1]/following::div[3]</value>
      <webElementGuid>26b2705e-e19b-4dc8-a813-b771e3647b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i'])[1]/following::div[4]</value>
      <webElementGuid>af8bbe18-1bc3-4479-9b61-b0fa793b1565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questions'])[1]/preceding::div[1]</value>
      <webElementGuid>73191ea7-1096-4aaa-b793-7fb6d91eb471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participants'])[2]/preceding::div[4]</value>
      <webElementGuid>c080c316-5d2d-4b03-ae03-0d4dc00b0d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4']/parent::*</value>
      <webElementGuid>4800b9ae-cc1c-4d12-b16b-35a597768d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>d5feb8a6-144f-4289-a97c-e0ae94d2a1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'metrics-bar-Questions-count' and (text() = '4' or . = '4')]</value>
      <webElementGuid>5ff8900f-d2e3-4f12-b262-5566957ade51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
