<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Total participants</name>
   <tag></tag>
   <elementGuidId>42357a8f-5eeb-4a20-870f-14c44272d7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#metrics-bar-Participants-count</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='metrics-bar-Participants-count']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>233ce9d9-5a8f-4846-8300-c5f1a9b4aa5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>dd67a73c-a746-4210-a842-a0451dfe675e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>metrics-bar-Participants-count</value>
      <webElementGuid>62b964d4-5e53-4a39-81e7-ce4138a635ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>979f63fa-bc77-4c55-abd6-286d34d69e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metrics-bar-Participants-count&quot;)</value>
      <webElementGuid>f1918a5b-134e-4f6a-a677-574953e42284</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='metrics-bar-Participants-count']</value>
      <webElementGuid>fb6e0688-9076-46b4-b594-618d6071944c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div[3]/div/div</value>
      <webElementGuid>e0d2bb9f-0c6d-4392-851c-1f4008cf23ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questions'])[1]/following::div[3]</value>
      <webElementGuid>1ea65893-6260-4a67-9f2b-dbecfc5dc3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sentiment'])[1]/following::div[7]</value>
      <webElementGuid>23dcc4da-db85-4348-a8bd-de254bea9c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participants'])[2]/preceding::div[1]</value>
      <webElementGuid>999f7048-e4ca-47e9-a786-1059f3b6def7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responses'])[2]/preceding::div[4]</value>
      <webElementGuid>2a56d065-5170-46c5-9cca-450b74e26282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8']/parent::*</value>
      <webElementGuid>328863e6-c908-45fd-81f0-6ccd8a5ef9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/div/div</value>
      <webElementGuid>e280cbe3-8903-4aee-ad6a-1cb5ba7e31f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'metrics-bar-Participants-count' and (text() = '8' or . = '8')]</value>
      <webElementGuid>624d0c05-b18b-4511-822a-6065993ce01b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
