<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Video responses percentage</name>
   <tag></tag>
   <elementGuidId>09a7ee6d-676d-4ead-9099-506a203d2885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#metrics-bar-Video-percentage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='metrics-bar-Video-percentage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3eaa008-ac2a-4f79-897c-e64b8d265644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>percentage</value>
      <webElementGuid>965ef345-afb2-44fc-a1b4-9c0c87908d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>metrics-bar-Video-percentage</value>
      <webElementGuid>eb3e2bc4-9c3d-4a21-9c95-7c0395d41e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>65%</value>
      <webElementGuid>ac418ef5-0c00-4a3b-9347-d4e061e7df0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metrics-bar-Video-percentage&quot;)</value>
      <webElementGuid>8876a8da-f7ce-4ae8-9cf6-0f2590928af1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='metrics-bar-Video-percentage']</value>
      <webElementGuid>b8390252-c615-41fe-b3de-c2ef664b1f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div[5]/div/div[2]</value>
      <webElementGuid>dd609418-21eb-403c-819e-1b208ad0e31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responses'])[2]/following::div[4]</value>
      <webElementGuid>1060c342-39cc-4575-8a1c-1090961c131e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participants'])[2]/following::div[8]</value>
      <webElementGuid>645ce9c3-97e9-4474-975f-56ba1a6f2b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video'])[1]/preceding::div[1]</value>
      <webElementGuid>9cb81f72-de34-4b59-b1ae-6ecbe2792be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audio'])[1]/preceding::div[5]</value>
      <webElementGuid>a67373a6-10f7-4df3-9630-fc69ba37c235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='65']/parent::*</value>
      <webElementGuid>58469706-c81c-4765-95c8-842e9431eb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[5]/div/div[2]</value>
      <webElementGuid>f55b0585-a254-4be1-99f2-ef24198daa3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'metrics-bar-Video-percentage' and (text() = '65%' or . = '65%')]</value>
      <webElementGuid>df450adb-76c6-4514-a479-4d96e71f4bb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
