<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit user button</name>
   <tag></tag>
   <elementGuidId>806f7fad-4b1e-4724-a916-73d4f8712a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='update-button-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#update-button-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f86491a-741c-4649-a3a3-a6bb395e9d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>update-button-0</value>
      <webElementGuid>78f37eda-abad-44e6-accb-6120afb06d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fk-content-action fk-content-edit-action ant-tooltip-open</value>
      <webElementGuid>a2eed469-fd4e-4cee-b1fc-2cc34f949f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;update-button-0&quot;)</value>
      <webElementGuid>befac16d-8e3f-49ed-b484-4eb1c536bd66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='update-button-0']</value>
      <webElementGuid>15638b23-448b-49f5-ae9c-bc54fd871dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/table/tbody/tr/td[4]/div/div</value>
      <webElementGuid>e80b8444-ef0d-4213-a69c-9b888dde9818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thu, 02 Feb 2023 08:42:22 GMT'])[1]/following::div[2]</value>
      <webElementGuid>e47f23ad-dfa0-44ee-a081-3f4e83ce18a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::div[3]</value>
      <webElementGuid>626f318a-6f94-49c0-84c4-34cf0fb710a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='waqasahmed2468@gmail.com'])[1]/preceding::div[3]</value>
      <webElementGuid>9b185094-ff72-474a-a719-bb846bcce2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager'])[1]/preceding::div[4]</value>
      <webElementGuid>f7594d5a-a700-48ae-8ae5-537a180cb484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div</value>
      <webElementGuid>b2dea02d-a132-4b99-8ffb-384a6d3927f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'update-button-0']</value>
      <webElementGuid>6585230c-99fb-405c-993b-131491a8b6e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
