<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Role admin</name>
   <tag></tag>
   <elementGuidId>a1915bdc-ba24-4082-bd63-eb8a6a892e83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='role-option-org-admin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#role-option-org-admin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc9a891b-2b05-47ff-a342-fccb41a89130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>role-option-org-admin</value>
      <webElementGuid>3e10d79a-2632-4ab3-902c-14de13478eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c25c25a5-0174-4b2a-97c0-eb5ba122c1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item ant-select-item-option ant-select-item-option-active</value>
      <webElementGuid>40e5b9c5-e8d4-40c8-9491-0ab9638774b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>856d3aa8-eb42-44b0-abd5-f90e46e034fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>3d1b8a49-9eec-4481-8683-17741957ef37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;role-option-org-admin&quot;)</value>
      <webElementGuid>e54d9cc9-d2b4-4839-9cc9-04d5b2656f21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='role-option-org-admin']</value>
      <webElementGuid>8bf0feb5-f643-40d1-8fdd-c8481da5ded0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='campaign-manager'])[1]/following::div[5]</value>
      <webElementGuid>cff5b907-01dc-4e58-82d9-6c17aa63731f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org-admin'])[1]/following::div[6]</value>
      <webElementGuid>0cf9bb09-e1bb-408f-ae64-96702515961a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager'])[3]/preceding::div[2]</value>
      <webElementGuid>02a4c33f-0258-42dd-8835-2c3c228c3357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>1ad0b430-3215-4fdd-aa9e-cf06008baf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'role-option-org-admin' and @title = 'Admin' and (text() = 'Admin' or . = 'Admin')]</value>
      <webElementGuid>6ee44b45-54bd-4461-b90b-1bd8485974c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
