<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Users Navbar</name>
   <tag></tag>
   <elementGuidId>a91c124a-e860-49fe-84e0-d88c98f88812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='side-nav-item-Users']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#side-nav-item-Users</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c374ef7d-bcbe-41a5-9f31-c224656a59b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>side-nav-item-Users</value>
      <webElementGuid>c4694878-0c88-4843-9423-85a7b1a58562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__SideNavItemStyled-sc-zzqga6-1 dLLvbR side-menu-item-active</value>
      <webElementGuid>dd5613d9-19b7-472e-a8eb-2a4d9a8c7d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>a73e0331-2ab8-4c45-ba3c-c149546e7d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-nav-item-Users&quot;)</value>
      <webElementGuid>e58b8f22-e88b-454f-bf7b-75b606f9b8ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='side-nav-item-Users']</value>
      <webElementGuid>59460a44-3e9c-4028-84e5-c61ccfcd2afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div</value>
      <webElementGuid>51bdeae1-0719-46a3-a8c9-d1838571c480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaigns'])[1]/preceding::div[4]</value>
      <webElementGuid>13fd3072-502e-4ffd-9b75-85705bbb2caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>d8b0e8fe-3286-41b2-b466-4c447ad97fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'side-nav-item-Users' and (text() = 'Users' or . = 'Users')]</value>
      <webElementGuid>647de054-b5b5-4f30-826b-df223a3be905</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
