<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Campaigns  - (2)Archived CampaignsAdd C_d12fcb</name>
   <tag></tag>
   <elementGuidId>de02282c-8a1d-4808-93e1-e87d9d3f9b7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sharedStyles__DashboardMainContainerStyle-sc-67rum6-6.fQHQWc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>190e18de-58f9-4c7f-9505-e454b8920592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sharedStyles__DashboardMainContainerStyle-sc-67rum6-6 fQHQWc</value>
      <webElementGuid>45490d83-788b-4c19-bff1-a0ccaa728a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Campaigns  - (2)Archived Campaigns+  Add CampaignFanvoice Test25/10/20222 Questions20 ResponsesFanvoice</value>
      <webElementGuid>e9df550f-ae13-4a1a-b50f-2d2225886bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;style__DashboardStyle-sc-1265zxf-0 hpOElW&quot;]/div[@class=&quot;sharedStyles__DashboardMainContainerStyle-sc-67rum6-6 fQHQWc&quot;]</value>
      <webElementGuid>73f9cf8b-a7c4-43c8-91f6-ee05f50d3876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]</value>
      <webElementGuid>6c22ec41-2958-4127-bb43-404a646e1e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::div[1]</value>
      <webElementGuid>cd5ed29e-fed8-4a16-8d21-fa7ee72be0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaigns'])[1]/following::div[1]</value>
      <webElementGuid>036ea39d-33c2-4e34-a7e0-e62a25387a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]</value>
      <webElementGuid>2382ce5c-008a-4774-b704-0ea8faec6c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Campaigns  - (2)Archived Campaigns+  Add CampaignFanvoice Test25/10/20222 Questions20 ResponsesFanvoice' or . = 'Campaigns  - (2)Archived Campaigns+  Add CampaignFanvoice Test25/10/20222 Questions20 ResponsesFanvoice')]</value>
      <webElementGuid>8b298b44-2cfe-4221-bfac-a8dcf19d5b34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
