<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add question button</name>
   <tag></tag>
   <elementGuidId>14cd2f56-c106-40a2-86b0-d8f346440c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-question-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add-question-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82b460c2-7c29-4092-b5e0-cc1ef097822f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-question-button</value>
      <webElementGuid>ec4f67b7-8ffc-41a3-b67c-721dbcde2611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__AddQuestionButton-sc-tdev96-0 hbaCWW</value>
      <webElementGuid>ccc7e508-eed2-4d8f-a4a8-80b4ca46b9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Add</value>
      <webElementGuid>dfb44ab1-1b3e-45f4-99b7-5ac3d7d31ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-question-button&quot;)</value>
      <webElementGuid>e63fcbe6-88e8-440b-8d8b-09c4bde39b74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='add-question-button']</value>
      <webElementGuid>53202057-ff3b-4525-ab58-ce2597dda637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div</value>
      <webElementGuid>a491b798-1106-4e99-88cf-5685783ec961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seconds'])[1]/following::div[2]</value>
      <webElementGuid>cfdb0c3f-5ac7-4dc2-a417-5e9635a1b4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::div[2]</value>
      <webElementGuid>f3ca697e-6a04-4b75-bd87-138b0385c23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/preceding::div[1]</value>
      <webElementGuid>089ba3eb-0d05-4728-bdc7-1af14312a532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Generate Questions'])[1]/preceding::div[1]</value>
      <webElementGuid>9496e8ae-ea21-41fe-afe2-3e96fe512c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+ Add']/parent::*</value>
      <webElementGuid>b79d9445-4614-4e30-9973-32dddb5fcdcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div</value>
      <webElementGuid>172abc80-f464-456d-9713-acecee60c0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'add-question-button' and (text() = '+ Add' or . = '+ Add')]</value>
      <webElementGuid>d8f6e40d-3c33-4874-8b20-42bbc96d85c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
