<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button add campaign</name>
   <tag></tag>
   <elementGuidId>3ac7b4ad-7fc2-4536-81b9-f284d943670a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-new-campaign-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add-new-campaign-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8baabd84-f4c8-419b-af7f-4a83e549c80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-new-campaign-btn</value>
      <webElementGuid>6f53a213-4bfc-4bec-ac97-71d333de1c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__BorderedButton-sc-1hf2caz-2 hXFcMz</value>
      <webElementGuid>3afd4ca9-fa4e-4b57-8300-46747aa4295b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+  Add Campaign</value>
      <webElementGuid>3eb5dd6e-850c-41e4-8c40-ebbad5abe0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-new-campaign-btn&quot;)</value>
      <webElementGuid>dfe27f36-9e87-4bd2-860e-1342a0ae7fca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='add-new-campaign-btn']</value>
      <webElementGuid>f73a7081-6c4d-4b7d-95e0-23269823b4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>61e2c965-c1b3-4a06-a752-391a4f0e2d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drafts'])[1]/following::div[1]</value>
      <webElementGuid>a17623e3-d2f7-4fe4-a254-662d86b85a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archived'])[1]/following::div[2]</value>
      <webElementGuid>226ec110-360d-4163-b8e3-4fbdfef7c609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='skippable test'])[1]/preceding::div[1]</value>
      <webElementGuid>ff9dbb77-2cc1-46d4-bc4a-7bc53cd4dcf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questions'])[1]/preceding::div[2]</value>
      <webElementGuid>f3527488-3fbc-438b-9e95-2a14505342bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+  Add Campaign']/parent::*</value>
      <webElementGuid>c93557cc-779e-4a51-b06b-50742a3b8dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>f6a8f3bc-6bf1-4d3e-8561-353074d542e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'add-new-campaign-btn' and (text() = '+  Add Campaign' or . = '+  Add Campaign')]</value>
      <webElementGuid>2a26f7f0-cb14-4855-8938-c3bc212f5888</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
