<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save  Exit</name>
   <tag></tag>
   <elementGuidId>f0d06320-7981-4816-aee0-6de9a137f0d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save-exit-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save-exit-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a06f5e5b-7d7c-431a-83ca-21196d08fdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__FilledButton-sc-1hf2caz-1 ggcmDn save-exit-button</value>
      <webElementGuid>b785c588-1ac8-4193-a998-9a9723b7e293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save-exit-button</value>
      <webElementGuid>b2115d23-1256-424a-adbd-4c3d8d0ee10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save &amp; Exit</value>
      <webElementGuid>5a7268d3-7632-4073-925d-77daef60cc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save-exit-button&quot;)</value>
      <webElementGuid>00936962-e311-4275-af53-aaf74057c5c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save-exit-button']</value>
      <webElementGuid>12925e0b-74b9-4ba0-9d53-8f4651cfdaf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[2]/div[4]/div[2]/div[2]/button</value>
      <webElementGuid>2d12e0b4-329a-4fd2-836a-d79819912697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finish'])[1]/following::button[1]</value>
      <webElementGuid>63b3f0f7-6d53-42ba-8219-ed87db20cdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[2]</value>
      <webElementGuid>8cad9837-69b2-47a1-93c1-fe65a95a3cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>8bbe490c-2f70-4df1-b3c9-0734c8e8ef8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>c9b8b5e6-5828-490b-b60b-2a1635c95603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save &amp; Exit']/parent::*</value>
      <webElementGuid>69a9958a-77f5-49bc-b94b-04d86cc5a1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>270cd71f-57ec-4d45-8d17-7a935249a0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'save-exit-button' and (text() = 'Save &amp; Exit' or . = 'Save &amp; Exit')]</value>
      <webElementGuid>805dfb68-58d8-4ac2-ab9d-0460d6ff19e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
