<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>campaign url</name>
   <tag></tag>
   <elementGuidId>66e987c7-11fd-4c3f-8023-0cfb18e8a9a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#campaign-url-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='campaign-url-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec8882c3-c69f-4c38-b860-8ccd7a4e8bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>21cc7e0d-f229-476b-a5f1-3b3d48033b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>campaignId</value>
      <webElementGuid>a91d308d-0d9f-4c44-bd2a-371f7587f221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>campaign-url-input</value>
      <webElementGuid>eb843dc7-82f9-445d-a048-2c1cd49cda3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>campaignid</value>
      <webElementGuid>61435506-59c8-4ac9-9e9f-b14ec07be4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd3af172-f90f-456b-8974-0edff88fad90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaign-url-input&quot;)</value>
      <webElementGuid>55a86eb3-0626-49f2-b076-7d7b690a2774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='campaign-url-input']</value>
      <webElementGuid>e7f5c5f6-9fd5-45b4-a563-4d141b6b5c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div/div[6]/div/div[2]/span/span/input</value>
      <webElementGuid>682f0f6b-7c3f-44e8-bb60-b0d6b6536088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>70f2b2ff-24d8-4e91-a8ce-1e91d28e37cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'campaignId' and @id = 'campaign-url-input' and @placeholder = 'campaignid' and @type = 'text']</value>
      <webElementGuid>fc8b9372-d3d3-4169-a8ff-007332aa0031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
