<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Consent Permission</name>
   <tag></tag>
   <elementGuidId>f22dacbb-a730-463f-b3c1-4fbe38f63725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#permission-checked</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='permission-checked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0fb80a22-df25-4d85-aadd-12f2adea9aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permission-checked</value>
      <webElementGuid>4bbbaad9-262e-4b77-b84a-c5863390916e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>fd52b062-bb05-4b4c-9618-98af8a2eaa52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permission-checked&quot;)</value>
      <webElementGuid>e8953a0b-1765-49a1-b198-7a6ca7a7cbbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='permission-checked']</value>
      <webElementGuid>7571b810-b6a8-4ee2-94ce-2c24c20311c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div/div[6]/div/div[2]/div/label/span[2]/span</value>
      <webElementGuid>13b822cd-7718-4c88-b090-2fc39c57e9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[4]</value>
      <webElementGuid>76525bc5-1462-4439-98de-0f9c6ee83f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::span[3]</value>
      <webElementGuid>1937b708-9d23-4faf-b709-a879f5d8e582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Logo'])[1]/preceding::span[5]</value>
      <webElementGuid>9ff9e551-45d9-44bd-b274-b927ed6c2ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/label/span[2]/span</value>
      <webElementGuid>c7c409d4-3891-403c-8c67-1afb01af4496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'permission-checked' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>7f9ee8ab-c3b2-4137-9ce5-cb81c0e42b22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
