<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit Question Save button</name>
   <tag></tag>
   <elementGuidId>c3f4920f-3706-4d31-aa19-1193885b083b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question-save-edit-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='question-save-edit-btn']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'question-save-edit-btn' and (text() = 'Save' or . = 'Save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3c417c3-38a2-4b00-88c3-3835e87ab5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>cd1cc125-ee64-4bf9-a5cc-02ba6bb78840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__FkButtonStyled-sc-13m638c-0 jvfzsl</value>
      <webElementGuid>ed43ed2c-8114-4cb6-9d11-73d8b8f73521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question-save-edit-btn</value>
      <webElementGuid>8bd4f802-85cd-4e17-8e60-49b0764d72ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>4da324ac-d7aa-4aec-9615-cf7b30cc2582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question-save-edit-btn&quot;)</value>
      <webElementGuid>7c04c8eb-f67b-4324-a3a6-d84f1245438d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='question-save-edit-btn']</value>
      <webElementGuid>c89bb022-2a0e-492a-bc00-909f8a3bda98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='questions-table']/tbody/tr/td[6]/div/button</value>
      <webElementGuid>908190b8-26fd-4a60-a843-c1e336308499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question1'])[1]/following::button[1]</value>
      <webElementGuid>d7a10d9b-4015-4a35-bea6-87cc986e2abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/following::button[1]</value>
      <webElementGuid>8cdabb9c-0e21-4390-8bb8-e99ba8d12230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>092be496-067e-4592-83a5-a1a3e0ce7d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trackers'])[1]/preceding::button[2]</value>
      <webElementGuid>af050a0c-26b1-4fbc-8960-d4cbab6957ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>e8312c17-039e-4f4f-8d88-137326e9dee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>184a4603-003f-4d7b-942f-055259c3962a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'question-save-edit-btn' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>98e8f3cd-5aec-423f-a819-a07d2083a96d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
