<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit Question add duration button</name>
   <tag></tag>
   <elementGuidId>93db9265-cc57-4a3c-81cf-a9e1bd70aded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='question-add-duration-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#question-add-duration-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>85d4eb8e-a82a-465c-8681-2b72d721336c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>81c9c043-7e1b-471e-80ee-7d65eecee3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question-add-duration-btn</value>
      <webElementGuid>102d8694-3322-4665-bbda-98e1b571186a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>e0883ef0-1394-4f89-8b4d-cad22959c6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question-add-duration-btn&quot;)</value>
      <webElementGuid>49c003e7-43cf-4412-9de8-6d188489dc47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='question-add-duration-btn']</value>
      <webElementGuid>d6c95825-9b0a-4160-abb3-4835cfa9af5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='questions-table']/tbody/tr/td[4]/div/span[2]</value>
      <webElementGuid>de1a2aa4-9f0d-49d4-ba48-216c97aa21d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::span[1]</value>
      <webElementGuid>ea3f6131-598f-4a2a-9e4d-f3e4e6cd3bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUESTION'])[1]/following::span[4]</value>
      <webElementGuid>89f43afe-01ed-409f-a306-9ca5dbf1bee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question1'])[1]/preceding::span[1]</value>
      <webElementGuid>444dd9d8-0d62-4c26-8993-5c2c93d7bb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::span[1]</value>
      <webElementGuid>ad37dfa9-a835-45b2-9e2f-e7e5e8b2a29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/span[2]</value>
      <webElementGuid>29e222bc-0b40-47f9-aa9b-4d07598a50d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'question-add-duration-btn' and (text() = '+' or . = '+')]</value>
      <webElementGuid>6144658e-6ac0-4419-a45b-a6b94095337f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
