<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__thankYouHeading</name>
   <tag></tag>
   <elementGuidId>6dbec2f2-10c7-47e0-9e4f-523d480d6ddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thank-you-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='thank-you-heading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a744602c-0cf5-4f0a-bf28-8f1511a26651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input style__TextFieldStyled-sc-1f0hnm9-0 kGzmKl text-field</value>
      <webElementGuid>300a95d7-2c9e-4765-8a09-e156e87b359e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>thankYouHeading</value>
      <webElementGuid>c643b95d-9f1a-4868-bda3-f2ebf3627650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thank-you-heading</value>
      <webElementGuid>bf886f6c-6efc-4f02-9323-ba1e5da6c80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Thank you</value>
      <webElementGuid>26267499-f0ea-45ff-a51f-91f1cbc51071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b26612c-2063-4b36-ab68-e83773bdf137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thank-you-heading&quot;)</value>
      <webElementGuid>d6c4165f-909b-4de3-b199-8f8bdf42d3dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='thank-you-heading']</value>
      <webElementGuid>81c09e84-9b0e-44fe-9212-78a998642ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>618be2d2-f931-4d88-b0c9-cf4d8d427b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>13ac3f4c-2a47-4f2e-88d8-2c3224b8d154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'thankYouHeading' and @id = 'thank-you-heading' and @placeholder = 'Thank you' and @type = 'text']</value>
      <webElementGuid>3dbbe5ac-cb96-4d4d-ade0-ced66724f3b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
