<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__getInTouchHeading</name>
   <tag></tag>
   <elementGuidId>d9346486-bcee-4694-bd18-3d57c6579a97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thank-you-heading-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='thank-you-heading-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a45ae94-c90c-4fa5-b5c1-6d71fd03b2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input style__TextFieldStyled-sc-1f0hnm9-0 kGzmKl text-field</value>
      <webElementGuid>ad9a170a-c561-48f7-b9a1-0f784bba50ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>getInTouchHeading</value>
      <webElementGuid>4819071e-c678-40ff-b2ad-7434e8398dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thank-you-heading-2</value>
      <webElementGuid>58224e19-9ca5-4be8-af0c-3ac756738181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Get In Touch</value>
      <webElementGuid>cf9bfa68-43a4-4b4f-b643-9cb26c1216e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff1f1f17-a9d4-409d-ac0f-9820c1f32e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thank-you-heading-2&quot;)</value>
      <webElementGuid>2cb57bef-9d78-4e6d-a78c-393264db6cc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='thank-you-heading-2']</value>
      <webElementGuid>32b85d1c-1b27-4824-8230-491928b2da15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div/div[4]/div/div[2]/input</value>
      <webElementGuid>ee51c9f6-0e49-45c7-bdc1-2c46dca2ee9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>996c38d5-ac9e-4d26-8251-bf9f39997d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'getInTouchHeading' and @id = 'thank-you-heading-2' and @placeholder = 'Get In Touch' and @type = 'text']</value>
      <webElementGuid>1458f1bd-228f-4d17-afe2-e31d36371057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
