<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__campaignName</name>
   <tag></tag>
   <elementGuidId>d794b041-a641-477d-80b6-f09b03d4250d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#campaign-name-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='campaign-name-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>589c621a-7eee-43b4-b86b-2ae725ca5edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input style__TextFieldStyled-sc-1f0hnm9-0 kGzmKl text-field</value>
      <webElementGuid>ffe51f90-2430-4d75-a74e-0c2a21b5fd96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>campaignName</value>
      <webElementGuid>9f6ca4d3-84fb-4126-912c-7bcc5bfc3686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>campaign-name-input</value>
      <webElementGuid>3aa91a7e-4b4d-47f7-bb9b-fe8cf78f2dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fanvoice</value>
      <webElementGuid>c40d3b21-dd60-4d6f-ba81-a48a9d0041db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f43660dc-daff-4241-b068-5ef818f0bf75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaign-name-input&quot;)</value>
      <webElementGuid>3afbd9dd-7c52-4090-9276-ba64af668f39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='campaign-name-input']</value>
      <webElementGuid>42144156-da21-47d2-a9cc-d36d8427f2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>b611e242-7a90-473e-b825-3e97173d328c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6799adc2-fa22-4b34-a68d-84c47c9c69e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'campaignName' and @id = 'campaign-name-input' and @placeholder = 'Fanvoice' and @type = 'text']</value>
      <webElementGuid>3e44328e-ff4c-4ec6-b19d-a3450dc3b263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
