<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Question Duration after edit</name>
   <tag></tag>
   <elementGuidId>e5f3d63f-dd7d-43a5-a7fa-f4c6ba76de50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='questions-table']/tbody/tr/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.duration-cell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3df1d29c-a433-4e99-a0e7-11cc8f518113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>duration-cell</value>
      <webElementGuid>8bf10f3e-ec5c-4615-b4e7-007b067cc9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>b7557d8d-cfdb-4990-a541-70e8dd35c902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;questions-table&quot;)/tbody[1]/tr[1]/td[@class=&quot;duration-cell&quot;]</value>
      <webElementGuid>390e5a0b-bae7-48f6-8c31-8e58e1901a3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='questions-table']/tbody/tr/td[4]</value>
      <webElementGuid>e0fa10d7-620f-4650-af70-1d528e86d0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUESTION'])[1]/following::td[4]</value>
      <webElementGuid>c801e441-8159-4203-bb6d-a492718b246c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DURATION'])[1]/following::td[4]</value>
      <webElementGuid>6ef5d687-9a91-4498-8a02-51c6b6402188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question1'])[1]/preceding::td[1]</value>
      <webElementGuid>a99e7c42-ff0a-4d63-a393-6d24d5d81714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trackers'])[1]/preceding::td[3]</value>
      <webElementGuid>b3466ab5-079a-4eeb-8616-c003a9c4e9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='35']/parent::*</value>
      <webElementGuid>9e406dea-383d-4745-98fa-59a1c77d2f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]</value>
      <webElementGuid>cfd15d59-10d9-4f3c-adad-2c3449c9aa78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '35' or . = '35')]</value>
      <webElementGuid>f018af35-1a19-4d8c-b789-5efad8e88202</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
