<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>terms and conditions</name>
   <tag></tag>
   <elementGuidId>3bc1cd5a-8614-4c7f-beca-83d615893dc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.public-DraftStyleDefault-block.public-DraftStyleDefault-ltr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rdw-wrapper-8543']/div[2]/div/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b424f69d-e1b9-4c44-843d-edf81b468be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-key</name>
      <type>Main</type>
      <value>fg368-0-0</value>
      <webElementGuid>a6826202-2d45-4010-a9e0-1e8d32c43fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>public-DraftStyleDefault-block public-DraftStyleDefault-ltr</value>
      <webElementGuid>27dc63e5-2f1e-4a68-906e-70837ea0a5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdw-wrapper-8543&quot;)/div[@class=&quot;editor-class rdw-editor-main&quot;]/div[@class=&quot;DraftEditor-root&quot;]/div[@class=&quot;DraftEditor-editorContainer&quot;]/div[@class=&quot;notranslate public-DraftEditor-content&quot;]/div[1]/div[1]/div[@class=&quot;public-DraftStyleDefault-block public-DraftStyleDefault-ltr&quot;]</value>
      <webElementGuid>769b9005-9b62-4e3b-b40f-3134eaea4aba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rdw-wrapper-8543']/div[2]/div/div[2]/div/div/div/div</value>
      <webElementGuid>4d17c097-8808-43c1-952c-3ea7f3638518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agree with terms &amp; conditions'])[1]/following::div[5]</value>
      <webElementGuid>e04f6f75-9829-4249-b055-8dddb34c9f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[16]</value>
      <webElementGuid>a11c27aa-b856-4ba8-bb76-f2422b54fb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::div[1]</value>
      <webElementGuid>0d3b561d-8519-465a-bf15-601d65ec1f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/div/div/div/div</value>
      <webElementGuid>7cd495e3-924d-4348-a713-a2fc40601d76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
