<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__question-section</name>
   <tag></tag>
   <elementGuidId>f8b3f2ef-8433-4b31-9b75-29d3eb1d46e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='question-textarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f85cf257-cc92-43fb-ad29-2a8bfb014e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>question-section</value>
      <webElementGuid>aa4f3837-9660-4c76-9a64-b0aa97ba423f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Explain you experience with Fanvoice?</value>
      <webElementGuid>65c5f51f-1b6f-4d2c-989f-f32a18cd04f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question-textarea</value>
      <webElementGuid>fe591612-0d90-4cb3-a1a8-7092f161b0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input style__TextAreaStyled-sc-1f0hnm9-2 jaJkTi add-question-field</value>
      <webElementGuid>15c4bac9-222a-498c-b7f4-67a5a3f80a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question-textarea&quot;)</value>
      <webElementGuid>7400c86c-9767-427d-9a71-f9321e188c6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='question-textarea']</value>
      <webElementGuid>193c07d8-06bf-4a6f-b8dd-87d72bcf1346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div[2]/div/div/textarea</value>
      <webElementGuid>83f0b318-22f2-42db-8253-fa941893443b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4de1c553-e830-47bd-96d4-a9bdf51cf871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'question-section' and @placeholder = 'Explain you experience with Fanvoice?' and @id = 'question-textarea']</value>
      <webElementGuid>a2be3820-1f18-4418-8038-a852d368c556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
