<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>ee4c56b7-1602-4f88-96f1-824745988f93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.authStyles__EmailButton-sc-lgk62z-6.jJOeYY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2bf695d8-4849-4cfc-aa07-8ec76d892efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2b13c35-fd89-41ca-8346-83507fc7fa53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>authStyles__EmailButton-sc-lgk62z-6 jJOeYY</value>
      <webElementGuid>9dcc3b20-def0-4524-87c8-ae48c6e10825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>73cd0fab-5240-4abc-9b3d-7c7b1b5abc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;authStyles__LoginPageWrapper-sc-lgk62z-0 jfLEbi&quot;]/div[@class=&quot;authStyles__RightSection-sc-lgk62z-2 iggOLg&quot;]/div[@class=&quot;authStyles__LoginContent-sc-lgk62z-3 mXMYn&quot;]/button[@class=&quot;authStyles__EmailButton-sc-lgk62z-6 jJOeYY&quot;]</value>
      <webElementGuid>2fdda0e2-3911-41cd-a86b-01654e1d0a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>957ccee0-115a-451b-b980-3d9246677dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/button</value>
      <webElementGuid>756fd2b6-f2c9-4020-b7c8-1d9796ae0500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to fanvoice'])[1]/following::button[1]</value>
      <webElementGuid>4a26da8e-6f8c-47ef-9709-1c077a7079e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fanvoice'])[1]/following::button[1]</value>
      <webElementGuid>8889ab15-99db-46ea-8f08-32a2e7bca218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in']/parent::*</value>
      <webElementGuid>a3d1b7ed-47fc-40e4-bc79-cc5a5ffef3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0f38df91-2f9c-490d-a3b6-73a7fe591de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>b7144e34-c079-4d62-85ce-6d2722776db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
