<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome to fanvoice_authStyles__Input_8d9327_1</name>
   <tag></tag>
   <elementGuidId>2b276870-0c49-446e-bbf2-5b5e032947c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edc3517e-165b-4b92-8f0c-ec2c263a6b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>authStyles__InputBox-sc-lgk62z-5 doVLQs email</value>
      <webElementGuid>59c10ab8-b232-4b6f-9697-d3f5bec5970e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2bcde6f4-32dc-492e-9392-7581bafe035f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>863b627c-815d-444d-a91c-4ceb1e3af894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;authStyles__LoginPageWrapper-sc-lgk62z-0 jfLEbi&quot;]/div[@class=&quot;authStyles__RightSection-sc-lgk62z-2 iggOLg&quot;]/div[@class=&quot;authStyles__LoginContent-sc-lgk62z-3 mXMYn&quot;]/input[@class=&quot;authStyles__InputBox-sc-lgk62z-5 doVLQs email&quot;]</value>
      <webElementGuid>e5e9abc0-7f7a-4efe-bcd9-99c4a854dd98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>b6dc5b9c-d71b-470d-9862-ddc106589b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/input[2]</value>
      <webElementGuid>e96e23ee-faad-48ec-868b-72b856238698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>ecd238f0-f649-46d2-99be-5b4fe7c33850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>4ce64836-fa5c-402c-b63a-586eb6571e03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
