<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome to fanvoice_authStyles__Input_8d9327</name>
   <tag></tag>
   <elementGuidId>74024ce9-72f6-4dcf-adf7-cb7e1b948247</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.authStyles__InputBox-sc-lgk62z-5.doVLQs.email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22c39ddb-e606-4847-b01a-e032ac73a902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>authStyles__InputBox-sc-lgk62z-5 doVLQs email</value>
      <webElementGuid>56439714-eae9-463a-9a21-c2da85216f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a380d7c-d6e4-4921-bf68-e3a74ccc6b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>0d7cdc4f-3d83-4f1b-a916-3d96fec0688a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;authStyles__LoginPageWrapper-sc-lgk62z-0 jfLEbi&quot;]/div[@class=&quot;authStyles__RightSection-sc-lgk62z-2 iggOLg&quot;]/div[@class=&quot;authStyles__LoginContent-sc-lgk62z-3 mXMYn&quot;]/input[@class=&quot;authStyles__InputBox-sc-lgk62z-5 doVLQs email&quot;]</value>
      <webElementGuid>c8765f68-2fca-44b0-a828-7c3bc02b652b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>57189ba2-0b53-462f-96b6-2cc276f438ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/input</value>
      <webElementGuid>dcb42dd6-0fc9-4fd1-b5f0-28009486edc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e39f05f5-3e19-48c1-ac73-a2ff118d3290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Email']</value>
      <webElementGuid>3e2e2d8e-4983-49e1-a67a-bae8cf5ef2d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
