<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Campaign Card</name>
   <tag></tag>
   <elementGuidId>aa6259c1-2e80-4013-8c38-02cd0f455b47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.style__CardHeader-sc-4gnvp0-2.cafOEi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ef25d91-e8f9-4194-943c-ac2da9965111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__CardHeader-sc-4gnvp0-2 cafOEi</value>
      <webElementGuid>0765a8ed-3282-46e6-a8b8-204169750454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Regression Testing Campaign17/01/2023</value>
      <webElementGuid>8ed69947-ee89-4b64-94a4-2e3dc29bf26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;style__DashboardStyle-sc-1265zxf-0 exXABA&quot;]/div[@class=&quot;dashboard-inner&quot;]/div[@class=&quot;sharedStyles__DashboardMainContainerStyle-sc-67rum6-7 hszqxc&quot;]/div[@class=&quot;style__ContainerStyled-sc-12mhbmd-0 cpDXyd&quot;]/div[@class=&quot;style__CardContainer-sc-4gnvp0-0 gkkFTS&quot;]/div[@class=&quot;style__CardStyled-sc-4gnvp0-1 eyoOQt&quot;]/div[@class=&quot;style__CardHeader-sc-4gnvp0-2 cafOEi&quot;]</value>
      <webElementGuid>9d321658-0116-45ff-a3f1-623e61084d0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div</value>
      <webElementGuid>f6836de8-d774-455d-a9c9-69d2dc9215ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+  Add Campaign'])[1]/following::div[4]</value>
      <webElementGuid>98cb1e2f-2dd4-4aad-8e55-eab6f8175fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drafts'])[1]/following::div[5]</value>
      <webElementGuid>016a725e-e83b-4113-afa2-8cf019df734e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questions'])[1]/preceding::div[1]</value>
      <webElementGuid>ada70296-0572-43be-9cf5-bf63b3b2249a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div</value>
      <webElementGuid>6f69bbf4-933a-49b2-94ef-768b9a42ec99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Regression Testing Campaign17/01/2023' or . = 'Regression Testing Campaign17/01/2023')]</value>
      <webElementGuid>3585d00c-17b3-4213-8d04-efefacacbf3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
