<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Archived</name>
   <tag></tag>
   <elementGuidId>88d712c2-8e6f-49cd-867a-45c772bbafbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-archived-campaigns</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select-archived-campaigns']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>21414871-f366-4ced-aec0-8366cac7c4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-archived-campaigns</value>
      <webElementGuid>37b496d2-7693-47e7-996f-e684f2f4451d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Archived</value>
      <webElementGuid>4c5e3c43-cf39-4d17-b264-95306d8c64f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-archived-campaigns&quot;)</value>
      <webElementGuid>73d1af27-4502-4c43-8774-f8d7394154dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select-archived-campaigns']</value>
      <webElementGuid>70ca5572-02b0-46be-8aa5-ca0775c906b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div[2]/ul/li[2]</value>
      <webElementGuid>fb08c25e-0aae-4111-a6b5-012de5405f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::li[1]</value>
      <webElementGuid>b6299191-d292-4f32-9fa3-741871bc3d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drafts'])[1]/preceding::li[1]</value>
      <webElementGuid>b6397a92-2e3e-474a-bca7-3ccb953896b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+  Add Campaign'])[1]/preceding::li[2]</value>
      <webElementGuid>84737e3b-55d9-4509-86a9-07420792c6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Archived']/parent::*</value>
      <webElementGuid>d6595f3a-239d-4fa1-abf5-e157892bc138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>119bc3de-6b91-4865-a4f9-28357e82664e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select-archived-campaigns' and (text() = 'Archived' or . = 'Archived')]</value>
      <webElementGuid>8f74ad71-2c4c-4eea-a500-330d08433e5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
