<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tab draft campaign</name>
   <tag></tag>
   <elementGuidId>1821a2f5-137b-41a9-9f9d-4cc92ff29bfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div[2]/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>83072b63-1f21-4eeb-b58a-ea5bdaf6bfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drafts </value>
      <webElementGuid>f5f44f22-46ba-4c4d-b477-e1996f605403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;style__DashboardStyle-sc-1265zxf-0 exXABA&quot;]/div[@class=&quot;dashboard-inner&quot;]/div[@class=&quot;sharedStyles__DashboardMainContainerStyle-sc-67rum6-7 hszqxc&quot;]/div[@class=&quot;style__SubHeaderStyled-sc-18x0jlo-0 ldZwRo&quot;]/div[@class=&quot;sharedStyles__UtilitiesDiv-sc-67rum6-1 iWidAI&quot;]/ul[@class=&quot;grouping&quot;]/li[3]</value>
      <webElementGuid>f0011429-62d5-4389-9e21-3417bfd40d59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div[2]/ul/li[3]</value>
      <webElementGuid>a2ddf62f-8437-4c5d-88ed-a3c049da0a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archived'])[1]/following::li[1]</value>
      <webElementGuid>66120bb2-c19a-4750-bb3d-58e206699b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::li[2]</value>
      <webElementGuid>3d7020be-3b0c-402a-b998-35a42a5376c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+  Add Campaign'])[1]/preceding::li[1]</value>
      <webElementGuid>a36f6f66-9122-4a97-93bb-10eab6097a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regression Testing Campaign'])[1]/preceding::li[1]</value>
      <webElementGuid>55e05ab6-f5e6-473c-8a2f-4b18f8674d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drafts']/parent::*</value>
      <webElementGuid>8ee88ed2-8c80-4153-999b-39890cc14af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>2c90aeed-bd5d-41f7-805a-51ca3cc00dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Drafts ' or . = 'Drafts ')]</value>
      <webElementGuid>76375a1f-846c-4921-b5b6-f889c4b49290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
