<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Start Video Recording button</name>
   <tag></tag>
   <elementGuidId>a4fbb927-305a-48af-b23f-d5cf8208e927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d8643dcb-86d1-4c3d-aeb5-43038c897f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1670314244917</value>
      <webElementGuid>612fad97-eb34-4760-92b3-fa92c69a305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-video-record-icon</value>
      <webElementGuid>70e888a1-0a3d-44f7-9b3e-d61c7f6b3d6b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
