<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Stop Video Recording button</name>
   <tag></tag>
   <elementGuidId>88cbf5ce-05bb-4caa-a781-1917b4f6410b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d0c1c747-2ff5-4960-9356-b351a3df16cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1670314313457</value>
      <webElementGuid>29c5b5f1-ecdf-43bb-8207-c236a068c181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-video-stop-record-icon</value>
      <webElementGuid>31acd83e-044c-4b8f-9da9-7e33449db22f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
