<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Record Audio</name>
   <tag></tag>
   <elementGuidId>e2ab947d-5faa-4446-8475-0a859e1ff7cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fk-audioCapture']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-audioCapture</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8707f6ed-e4e6-4335-bb16-9906737a60d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-audioCapture</value>
      <webElementGuid>55e7b1fe-5798-490e-be0e-f3091f882fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__WidgetTile-sc-4fv1f1-3 bpXZMD</value>
      <webElementGuid>605a23a1-f2b9-4876-aa75-0f14785032d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Record Audio</value>
      <webElementGuid>75512707-d726-40c0-8737-3c9edd426b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-audioCapture&quot;)</value>
      <webElementGuid>312baa76-c024-4f5c-a759-64bf4c61d2c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fk-audioCapture']</value>
      <webElementGuid>686d4e96-9170-4c8c-a6f6-ab058498cd7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-dktp-home-screen']/div[2]/div/div[2]</value>
      <webElementGuid>f620477e-5824-4b84-bbf5-3b3119add1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automated Test Campaign by Waqas'])[1]/following::div[4]</value>
      <webElementGuid>7229bc7f-3aae-4026-8254-07989874499b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'fk-audioCapture', '&quot;', ')')])[1]/preceding::div[5]</value>
      <webElementGuid>0fadf0ef-2e13-4a06-844e-dcbca19cadf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>ea655cae-7fa0-4ff3-954d-722b4e2556c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'fk-audioCapture' and (text() = 'Record Audio' or . = 'Record Audio')]</value>
      <webElementGuid>ed29ac46-a12d-481a-a8d3-0631c2156732</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
