<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form input job title</name>
   <tag></tag>
   <elementGuidId>3b087c5a-64c3-40f2-814b-67fa728d8a02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fk-jobTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk-jobTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0df57fc8-bdcf-4667-b252-6fff2ca84c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobTitle</value>
      <webElementGuid>58b99f75-8e3f-4fed-be3e-5e9cbed96e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Job Title</value>
      <webElementGuid>6501edff-e330-454d-abfc-5051c44dc919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fk-input fk-jobTitle </value>
      <webElementGuid>c2bbee74-cd01-452d-aab8-da4c89e61eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk-jobTitle</value>
      <webElementGuid>d4a1220c-7ace-4446-acd2-ea919937792c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>fca4f664-9ab6-41cc-9639-837a433f7b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>334aeafd-231d-416c-9638-9fe6fc0fc026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk-jobTitle&quot;)</value>
      <webElementGuid>efa25284-46a2-4ff4-bdad-37fa4ee37658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fk-jobTitle']</value>
      <webElementGuid>96eaa5bb-f59a-441c-bfb5-fa8d802d427b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fk-mobile-thankyou-screen']/form/div/input[3]</value>
      <webElementGuid>4d1a62b5-0499-4563-908a-a8199a6fd366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>4b794449-ae46-4240-9859-91c51524c52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'jobTitle' and @placeholder = 'Job Title' and @id = 'fk-jobTitle' and @type = 'text']</value>
      <webElementGuid>9c112eeb-a6fb-4657-a879-06d7f5fd4d7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
