<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your browser does not support HTML vide_0194bc</name>
   <tag></tag>
   <elementGuidId>24458d46-64d8-46dc-9097-c28da17b1488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='card-container']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d9024bcf-6fdf-43f7-830b-a5c643167208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-column</value>
      <webElementGuid>0cb2334e-36b8-4a56-9abd-c9f71e1f7e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your browser does not support HTML video.00:00 /00:04This is Question 01 for Testing?0%WWaqasi18mTranscriptionHello, hello. Mike testing. Hello. Hello 1.</value>
      <webElementGuid>07c9ed8e-3d9c-4357-9c8b-52351f684010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-container&quot;)/div[@class=&quot;card-column&quot;]</value>
      <webElementGuid>ad773ee7-e6bd-4bd1-a05c-f64b4c1ee6b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-container']/div</value>
      <webElementGuid>554486f0-d15c-485a-9ca9-9d6fda9d8b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audio'])[1]/following::div[5]</value>
      <webElementGuid>e74af001-7b00-4128-8523-80aed4f61b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video'])[1]/following::div[9]</value>
      <webElementGuid>1a3148ca-63a7-4dc7-8a4e-bc58059e633c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/div</value>
      <webElementGuid>b8032df1-119e-41a9-9f69-c89298386a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your browser does not support HTML video.00:00 /00:04This is Question 01 for Testing?0%WWaqasi18mTranscriptionHello, hello. Mike testing. Hello. Hello 1.' or . = 'Your browser does not support HTML video.00:00 /00:04This is Question 01 for Testing?0%WWaqasi18mTranscriptionHello, hello. Mike testing. Hello. Hello 1.')]</value>
      <webElementGuid>37ae4ab0-f1a7-4749-8df1-f3f37f05ed50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
