<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Waqas</name>
   <tag></tag>
   <elementGuidId>6be3c76f-f1d3-4a2f-9b5c-f51173739a34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.fk-user-name-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='responseCard0']/div[2]/div/div[2]/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>a6dc1551-7b7c-457c-b2c1-cdd130a3edae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fk-user-name-text</value>
      <webElementGuid>77abad47-49c9-4dbf-a5c9-ba8bb4ffba89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Waqas</value>
      <webElementGuid>e98a5ada-3298-4ef1-90d0-7f358c018424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responseCard0&quot;)/div[@class=&quot;style__Content-sc-1eu4ljs-5 foUogx fk-card-content&quot;]/div[@class=&quot;style__IntroWrapper-sc-1eu4ljs-8 fPGgKM fk-user-wrapper&quot;]/div[@class=&quot;style__TextContainer-sc-1eu4ljs-10 iSuGSQ fk-user-meta&quot;]/div[@class=&quot;fk-user-name&quot;]/h4[@class=&quot;fk-user-name-text&quot;]</value>
      <webElementGuid>9d572c3e-8e66-4f10-901d-cfb0c5a0ca73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responseCard0']/div[2]/div/div[2]/div/h4</value>
      <webElementGuid>fdc129ab-d448-4491-902b-929ea240db35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W'])[2]/following::h4[1]</value>
      <webElementGuid>062358ba-2228-49d9-8ebf-bdc55443a762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[1]/following::h4[1]</value>
      <webElementGuid>23a876cf-388a-4dd6-bbb3-38a9bbf641ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i'])[2]/preceding::h4[1]</value>
      <webElementGuid>d71fad9c-cd2f-4111-9b3e-8f262802352a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transcription'])[1]/preceding::h4[1]</value>
      <webElementGuid>2ee1937a-b65a-423d-a994-796db62e45e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Waqas']/parent::*</value>
      <webElementGuid>872c81a6-2dad-4085-aee0-cc5d51150584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/h4</value>
      <webElementGuid>93f7226f-046c-418d-a23e-86b097581341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Waqas' or . = 'Waqas')]</value>
      <webElementGuid>2e735bba-77c9-422e-a002-0a2ab4a77036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
