<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Automated Test Campaign 02_logo</name>
   <tag></tag>
   <elementGuidId>ad501e79-edbd-441d-bfc3-cce86c8ae075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f302c7b9-7908-4ed2-80ba-4299c13703cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>05241f04-4426-4e22-b861-a785dd1bf31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/admin/images/logo.png</value>
      <webElementGuid>6eb4ffc7-9582-4ec8-993f-3be128b1c50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>copmany-logo</value>
      <webElementGuid>70c44813-6449-4aaf-8d39-a90d45d7d432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;style__DashboardStyle-sc-1265zxf-0 hpOElW&quot;]/div[@class=&quot;style__HeaderStyled-sc-1441c0w-0 dBchoU&quot;]/div[@class=&quot;style__Avatarcontainer-sc-1441c0w-1 bSmOfj&quot;]/div[@class=&quot;logo-wrapper&quot;]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>be6b53a3-1e44-4079-80f2-33ab64411b09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/img</value>
      <webElementGuid>f8b4c9c6-e67c-4bb2-bf5e-543a6eaea9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='copmany-logo']</value>
      <webElementGuid>e9160e38-3a35-40cd-9156-c6413db2c280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>84e76dc5-4bcc-4c4a-be6d-f399a8b34bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/admin/images/logo.png' and @alt = 'copmany-logo']</value>
      <webElementGuid>aa0deeae-d9c7-4c2d-859e-52a0e827e660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
