      # ./katalonc -noSplash -retry=0 -testSuiteCollectionPath="Test Suites/4- Video App Suite - Feedback App" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true"
      # - name: Katalon Studio Github Action
      #   uses: katalon-studio/katalon-studio-github-action@v2
      #   with:
      #     version: "7.5.5"
      #     projectPath: "${{ github.workspace }}"
      #     args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/4- Video App Suite - Feedback App" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'

name: Automation CI

on:
  workflow_dispatch:

jobs:
  katalon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java SDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Katalon Studio
      run: |
        cd $HOME
        curl -LO https://github.com/katalon-studio/katalon-studio/releases/download/v7.9.1/Katalon_Studio_Linux_64-7.9.1.tar.gz
        tar -xzf Katalon_Studio_Linux_64-7.9.1.tar.gz
        $HOME
        ls

    - name: Run Katalon Studio tests
      env:
        KATALON_ROOT_DIR: $HOME/Katalon_Studio_Linux_64-7.9.1
        KATALON_OPTS: -runMode=console -projectPath=$GITHUB_WORKSPACE/AdminConcolev2.prj -retry=0 -testSuitePath=Test Suites/4- Video App Suite - Feedback App
      run: |
        $HOME
        ls
        cd $KATALON_ROOT_DIR
        ./katalonc $KATALON_OPTS
